"use client";
import { RecordHistory } from "./record-history";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { intelligenceApi } from "@/lib/client";
import type { ResearchRecord } from "@/lib/research";
import { Choice,Field,Status } from "./ui";
import { BusyButton,ErrorMessage } from "./workflow-ui";
export function AnalysisReview({studyId,analysisId,section,index,item,records,enabled,onRefresh}:{studyId:string;analysisId:string;section:"themes"|"findings";index:number;item:any;records:ResearchRecord[];enabled:boolean;onRefresh:()=>Promise<void>}){
  const previous=records.filter(r=>r.kind==="classification"&&r.payload.method==="human_analysis_review"&&r.payload.analysisId===analysisId&&r.payload.section===section&&r.payload.index===index).sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0],[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[v,setV]=useState({verdict:previous?.payload.verdict||"edited",title:previous?.payload.title||item.title,interpretation:previous?.payload.interpretation||item.description||item.explanation,explanation:previous?.payload.explanation||""});
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await intelligenceApi("review_analysis",{studyId,analysisId,section,index,expectedUpdatedAt:previous?.updated_at,...v});await onRefresh();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="mt-5 border-t pt-4">{previous&&<div className="mb-4 space-y-3 rounded-lg bg-secondary/50 p-4"><Status value={previous.payload.verdict}/><h4 className="text-sm font-semibold">{previous.payload.title}</h4><p className="text-sm leading-7">{previous.payload.interpretation}</p><p className="text-sm leading-6 text-muted-foreground"><strong>Reviewer’s rationale: </strong>{previous.payload.explanation}</p></div>}<Button size="sm" variant="outline" disabled={!enabled} onClick={()=>setOpen(true)}>{previous?"Update human review":"Review this interpretation"}</Button>{previous&&<RecordHistory record={previous} enabled={!studyId.startsWith("example")}/>}<Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Review the interpretation</DialogTitle><DialogDescription>The original model output remains intact. Your assessment is stored separately with its evidence and revision history.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-5"><Field label="Review decision"><Choice value={v.verdict} onChange={verdict=>setV({...v,verdict})} options={[["accepted","Accept with rationale"],["edited","Revise interpretation"],["rejected","Reject interpretation"]]}/></Field><Field label="Reviewed title"><Input required value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></Field><Field label="Your interpretation"><Textarea required rows={5} value={v.interpretation} onChange={e=>setV({...v,interpretation:e.target.value})}/></Field><Field label="Evidence and rationale"><Textarea required rows={4} value={v.explanation} onChange={e=>setV({...v,explanation:e.target.value})} placeholder="Why is this interpretation justified or misleading? Include the counterexamples you considered."/></Field><ErrorMessage message={error}/><BusyButton busy={busy}>Save human review</BusyButton></form></DialogContent></Dialog></div>;
}
