"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { ArrowUpRight,MessageCircleQuestion } from "lucide-react";
import { displayDate,intelligenceApi } from "@/lib/client";
import type { ResearchRecord,Run,Study } from "@/lib/research";
import { Choice,Field,Note,SourceLink,Status } from "./ui";
import { Card,EmptyState,ErrorMessage,BusyButton } from "./workflow-ui";
export function Challenges({study,records,runs,enabled,onOpen,onRefresh}:{study:Study;records:ResearchRecord[];runs:Run[];enabled:boolean;onOpen:(id:string)=>void;onRefresh:()=>Promise<void>}){
  const reviews=records.filter(r=>r.kind==="review"),challenges=records.filter(r=>r.kind==="challenge"),canResolve=enabled&&study.access_role!=="viewer";
  const [open,setOpen]=useState(false),[reviewId,setReviewId]=useState(reviews[0]?.id||""),[message,setMessage]=useState(""),[url,setUrl]=useState(""),[excerpt,setExcerpt]=useState(""),[resolving,setResolving]=useState<ResearchRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await intelligenceApi("challenge",{studyId:study.id,reviewId,message,evidenceUrl:url,excerpt});await onRefresh();setOpen(false);setMessage("");setUrl("");setExcerpt("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="space-y-6"><Card title="A finding can be questioned" description="Clients can challenge an interpretation, provide a source, and follow the resolution. The original finding and the version they saw stay in the record." action={<Button disabled={!enabled||!reviews.length} onClick={()=>setOpen(true)}><MessageCircleQuestion size={15}/>Challenge a finding</Button>}><div className="grid grid-cols-3 gap-4">{["open","investigating","resolved"].map(status=><div key={status} className="rounded-lg bg-secondary/50 p-4"><p className="text-2xl font-semibold tabular-nums">{challenges.filter(c=>c.payload.status===status).length}</p><p className="mt-2 text-sm capitalize text-muted-foreground">{status}</p></div>)}</div></Card><ErrorMessage message={error}/>{challenges.length?challenges.map(c=><Card key={c.id} title={c.payload.message} description={`Submitted ${displayDate(c.created_at)}`} action={<Status value={c.payload.status}/>}><div className="rounded-lg bg-secondary/50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Finding at the time of the challenge</p><blockquote className="mt-3 text-base leading-7">{c.payload.findingSnapshot.payload.claim}</blockquote><p className="mt-2 text-sm leading-6 text-muted-foreground">{c.payload.findingSnapshot.payload.explanation}</p><Button className="mt-3" size="sm" variant="outline" onClick={()=>onOpen(c.payload.findingSnapshot.payload.runId)}>Inspect original answer<ArrowUpRight size={13}/></Button></div>{c.payload.evidenceUrl&&<p className="mt-4 text-sm"><SourceLink url={c.payload.evidenceUrl}/></p>}{c.payload.excerpt&&<blockquote className="mt-4 border-l-2 border-blue-200 pl-4 text-sm leading-7">{c.payload.excerpt}</blockquote>}{c.payload.replies.map((r:any,i:number)=><div key={i} className="mt-4 border-t pt-4"><p className="text-xs text-muted-foreground">Research team · {displayDate(r.createdAt)}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{r.message}</p></div>)}{c.payload.resolution&&<div className="mt-4 rounded-lg border border-blue-200 p-4"><h3 className="text-sm font-semibold">Recorded resolution</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{c.payload.resolution}</p>{(c.payload.evidenceRunIds||[]).map((id:string)=><Button key={id} className="mt-3 mr-2" size="sm" variant="outline" onClick={()=>onOpen(id)}>Resolution evidence<ArrowUpRight size={13}/></Button>)}</div>}<Button variant="outline" className="mt-5" disabled={!canResolve} onClick={()=>setResolving(c)}>Respond and update status</Button></Card>):<EmptyState title="No open disagreements">Once a claim has a human assessment, clients can challenge it here. Questions on shared report snapshots also remain available in Client reports.</EmptyState>}<Note>Resolving a challenge records the team’s response. It does not silently edit or verify the original finding; any assessment change must be saved separately with its own evidence.</Note>
    <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Challenge a finding</DialogTitle><DialogDescription>Explain what you disagree with and include the best available evidence.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><Field label="Finding"><Choice value={reviewId} onChange={setReviewId} options={reviews.map(r=>[r.id,r.payload.claim])}/></Field><Field label="What needs to be reconsidered?"><Textarea required rows={4} value={message} maxLength={8000} onChange={e=>setMessage(e.target.value)}/></Field><Field label="Evidence URL · optional"><Input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></Field><Field label="Exact supporting excerpt · optional"><Textarea rows={4} value={excerpt} maxLength={12000} onChange={e=>setExcerpt(e.target.value)}/></Field><ErrorMessage message={error}/><BusyButton busy={busy}>Submit challenge</BusyButton></form></DialogContent></Dialog>{resolving&&<Resolution record={resolving} study={study} runs={runs} onClose={()=>setResolving(null)} onRefresh={onRefresh}/>}</div>;
}
function Resolution({record,study,runs,onClose,onRefresh}:{record:ResearchRecord;study:Study;runs:Run[];onClose:()=>void;onRefresh:()=>Promise<void>}){
  const [message,setMessage]=useState(""),[status,setStatus]=useState(record.payload.status),[resolution,setResolution]=useState(record.payload.resolution||""),[ids,setIds]=useState<string[]>(record.payload.evidenceRunIds||[]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await intelligenceApi("resolve_challenge",{studyId:study.id,id:record.id,expectedUpdatedAt:record.updated_at,message,status,resolution,evidenceRunIds:ids});await onRefresh();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Respond to the challenge</DialogTitle><DialogDescription>{record.payload.message}</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-5"><Field label="Response"><Textarea required rows={4} value={message} onChange={e=>setMessage(e.target.value)}/></Field><Field label="Status"><Choice value={status} onChange={setStatus} options={[["open","Open"],["investigating","Investigating"],["resolved","Resolved"],["declined","Declined with explanation"]]}/></Field><Field label="Resolution rationale"><Textarea rows={4} required={["resolved","declined"].includes(status)} value={resolution} onChange={e=>setResolution(e.target.value)}/></Field><fieldset className="max-h-48 space-y-2 overflow-auto"><legend className="mb-2 text-sm font-semibold">Supporting observations</legend>{runs.map(r=><label key={r.id} className="flex gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={ids.includes(r.id)} onChange={e=>setIds(e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/>{r.prompt}</label>)}</fieldset><ErrorMessage message={error}/><BusyButton busy={busy}>Save response and status</BusyButton></form></DialogContent></Dialog>;
}
