"use client";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { reviewFacts, inspectClaim, type NativeCitation, type SelectedClaim } from "@/lib/claims";
import { environments, providerNames, type ResearchRecord, type Run } from "@/lib/research";
import { Note, SourceLink, Status } from "./ui";

function CitationCard({ citation }: { citation: NativeCitation }) {
  const n = citation.native;
  return <div className="space-y-3 rounded-lg border bg-white p-4"><SourceLink url={n.url || ""} title={n.title || n.url || "Citation metadata"}/>{typeof n.cited_text === "string" && <div><p className="mb-1 text-xs text-muted-foreground">Source excerpt supplied by provider</p><blockquote className="evidence-text border-l-2 pl-3 text-sm">{n.cited_text}</blockquote></div>}<details className="text-xs text-muted-foreground"><summary className="cursor-pointer">Inspect original citation fields</summary><p className="my-2 break-all font-mono">{citation.raw_path}</p><pre className="raw-json">{JSON.stringify(n, null, 2)}</pre></details></div>;
}
export function ClaimPanel({ claim, run, records, demo, onClose, onReview, onEditReview, readOnly=false }: { readOnly?:boolean; claim: SelectedClaim | null; run: Run; records: ResearchRecord[]; demo: boolean; onClose: () => void; onReview: (claim: SelectedClaim) => void; onEditReview: (r: ResearchRecord) => void }) {
  const evidence = claim ? inspectClaim(run, claim, records) : null;
  return <Sheet open={!!claim} onOpenChange={open => { if (!open) onClose(); }}><SheetContent className="w-full overflow-y-auto bg-white sm:max-w-[640px]"><SheetHeader className="border-b px-6 py-6"><SheetTitle>Investigate this passage</SheetTitle><SheetDescription>Follow its recorded attribution and inspect the evidence behind each review.</SheetDescription></SheetHeader>{claim && evidence && <div className="space-y-7 px-6 pb-8">
    <section><div className="mb-3 flex flex-wrap gap-2"><Badge variant="outline">Observed answer text</Badge>{demo && <Badge variant="outline">Synthetic example</Badge>}</div><blockquote className="evidence-text rounded-lg border-l-4 border-l-primary bg-blue-50 p-4 text-base">{claim.text}</blockquote><p className="mt-3 text-xs text-muted-foreground">{providerNames[run.provider]} · {environments[run.environment]} · {run.model}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={async()=>{await navigator.clipboard.writeText(window.location.href);}}>Copy passage link</Button><Button size="sm" variant="outline" onClick={async()=>{const module=await import("@/lib/client");try{const data=await module.readWorkspace("draft",{studyId:run.study_id,name:"pinned-evidence"});const pins=data.draft?.payload?.pins||[];if(!pins.some((p:any)=>p.runId===run.id&&p.start===claim.start&&p.segmentIndex===claim.segmentIndex)){await module.workspaceApi("draft",{studyId:run.study_id,name:"pinned-evidence",version:data.draft?.version||0,payload:{pins:[...pins.slice(-19),{runId:run.id,...claim,prompt:run.prompt,provider:run.provider}]}});window.dispatchEvent(new Event("evidence-pinned"));}}catch(e){(await import("sonner")).toast.error((e as Error).message);}}} disabled={demo}>Pin passage</Button></div><details className="mt-3 text-xs"><summary className="cursor-pointer text-muted-foreground">Exact location and question</summary><p className="evidence-text mt-3 text-sm">{run.prompt}</p><p className="mt-2 break-all font-mono">{run.normalized?.segments[claim.segmentIndex]?.raw_path}.text · positions {claim.start}–{claim.end} (UTF-16, end exclusive)</p></details></section>
    <section className="space-y-3"><h3 className="text-base font-semibold">Citations located in this passage</h3>{evidence.located.length ? evidence.located.map((c, i) => <CitationCard key={i} citation={c}/>) : <p className="text-sm leading-6 text-muted-foreground">No citation can be precisely located here from the available metadata. This does not establish that the statement is unsupported.</p>}{!!evidence.located.length && <p className="text-xs leading-5 text-muted-foreground">Provider-reported citation positions overlap this passage. That association is not a verification of the claim or proof of how it was generated.</p>}</section>
    {!!evidence.block.length && <section className="space-y-3"><h3 className="text-base font-semibold">Citations attached to the answer block</h3><p className="text-sm leading-6 text-muted-foreground">These belong to the surrounding text block. An exact link to this sentence has not been established.</p>{evidence.block.map((c, i) => <CitationCard key={i} citation={c}/>)}</section>}
    {!!evidence.elsewhere.length && <details className="text-sm"><summary className="cursor-pointer font-medium">{evidence.elsewhere.length} citation(s) located elsewhere in this answer block</summary><div className="mt-3 space-y-3">{evidence.elsewhere.map((c, i) => <CitationCard key={i} citation={c}/>)}</div></details>}
    <section className="space-y-4 border-t pt-5"><div className="flex items-center justify-between gap-3"><h3 className="text-base font-semibold">Researcher assessment</h3><Button size="sm" disabled={demo || readOnly || claim.text.length > 6000} onClick={() => { onClose(); onReview(claim); }}>Review passage</Button></div>{evidence.reviews.length ? evidence.reviews.map(review => <div key={review.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center gap-2"><Status value={review.payload.verdict}/><Badge variant="outline">{review.payload.evidenceLevel.replaceAll("_", " ")}</Badge><Button size="sm" variant="ghost" disabled={demo || readOnly} className="ml-auto" onClick={() => { onClose(); onEditReview(review); }}>Edit</Button></div><p className="evidence-text text-sm">{review.payload.explanation}</p>{!demo&&<Button asChild size="sm" variant="outline"><a href={`/?study=${run.study_id}&section=challenges&review=${review.id}`}>Challenge this finding</a></Button>}{reviewFacts(review, records).map(fact => { return fact ? <div key={fact.id} className="space-y-2 rounded bg-slate-50 p-3 text-sm"><p className="font-medium">{fact.payload.claim}</p><blockquote className="evidence-text border-l-2 pl-3">{fact.payload.excerpt}</blockquote><SourceLink url={fact.payload.source} title="Open reference source"/><p className="text-xs text-muted-foreground">{review.payload.factSnapshots ? "Saved with this review · " : "Current reference · "}{fact.payload.status.replaceAll("_", " ")} · Checked {fact.payload.checkedAt} · {fact.payload.product || "Product not specified"}</p></div> : null; })}{review.payload.impact && <p className="evidence-text text-sm"><strong>Why it matters: </strong>{review.payload.impact}</p>}{review.payload.recommendation && <p className="evidence-text text-sm"><strong>Recommended action: </strong>{review.payload.recommendation}</p>}</div>) : <p className="text-sm leading-6 text-muted-foreground">This passage has not been reviewed. A review can link it to dated source excerpts, explain its significance, and recommend an action.</p>}</section>
    <Note>What remains unknown: the model’s private reasoning, why it selected or omitted a source, and whether a separately checked page matches what the model saw. Reference passages are supplied by the researcher unless labeled as provider excerpts.</Note>
  </div>}</SheetContent></Sheet>;
}
