"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Check, ExternalLink, KeyRound, Loader2, ShieldCheck, Unplug } from "lucide-react";
import { api, readWorkspace, workspaceApi, monitorApi } from "@/lib/client";
import { providerNames, type Provider, type Study } from "@/lib/research";
import { Choice, Field, Note, Status } from "./ui";
import type { Connections } from "./collect";
export function ConnectionsPage({value,onChange,enabled,study,onSaved}:{value:Connections;onChange:(c:Connections)=>void;enabled:boolean;study?:Study;onSaved:()=>Promise<void>}){
  const [saved,setSaved]=useState<any[]>([]),[grants,setGrants]=useState<any[]>([]),[vault,setVault]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[allowance,setAllowance]=useState(100),[queueKey,setQueueKey]=useState(""),[probe,setProbe]=useState<string|null>(null);
  const owner=!study||!study.access_role||study.access_role==="owner";
  async function reload(){if(!enabled)return;const data=await readWorkspace("connections",study?{studyId:study.id}:{});setSaved(data.connections);setGrants(data.grants);setVault(data.vaultReady);}
  useEffect(()=>{void reload().catch(e=>setError(e.message));},[study?.id,enabled]);
  const update=(p:Provider,v:Partial<Connections[Provider]>)=>onChange({...value,[p]:{...value[p],...v}});
  async function perform(id:string,fn:()=>Promise<void>){setBusy(id);setError("");try{await fn();await reload();await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  async function check(p:Provider){await perform(p,async()=>{const data=await api("models",{provider:p,...(value[p].key?{key:value[p].key}:{connectionId:value[p].connectionId})});update(p,{models:data.models,checked:true});});}
  async function save(p:Provider){await perform(p,async()=>{const own=saved.find(c=>c.id===value[p].connectionId);const data=await workspaceApi("connection",{id:own?.id,provider:p,label:providerNames[p],model:value[p].model,key:value[p].key||undefined});if(study&&owner)await workspaceApi("grant_connection",{studyId:study.id,connectionId:data.id,requestLimit:Math.max(allowance,grants.find(g=>g.id===data.id)?.request_limit||0)});update(p,{connectionId:data.id,key:""});});}
  const urls:Record<Provider,string>={openai:"https://platform.openai.com/api-keys",anthropic:"https://platform.claude.com/settings/keys",gemini:"https://aistudio.google.com/apikey",perplexity_api:"https://www.perplexity.ai/settings/api",xai:"https://console.x.ai"};
  return <div className="max-w-5xl space-y-6"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-white p-5"><ShieldCheck className="mb-3 text-primary"/><h2 className="font-semibold">Encrypted at rest</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Saved credentials stay on the server. They never enter evidence, reports, or client responses.</p></div><div className="rounded-xl border bg-white p-5"><KeyRound className="mb-3 text-primary"/><h2 className="font-semibold">A budget per brand</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Authorize a fixed number of requests for each connection. Uncertain requests still consume the allowance.</p></div><div className="rounded-xl border bg-white p-5"><Check className="mb-3 text-primary"/><h2 className="font-semibold">Explicit methods</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">API experiments and consumer-app observations keep separate identities and measurements.</p></div></div>
    {!vault&&enabled&&<Note warning>Secure storage is not active in this environment. You can use a key temporarily in this tab; an operator must configure the vault before saving credentials.</Note>}{error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-destructive">{error}</p>}
    {study&&owner&&<div className="flex flex-wrap items-end gap-4 rounded-xl border bg-white p-5"><div className="max-w-sm"><Field label="Initial request allowance per saved connection" hint="Lifetime allowance for this brand, including analysis requests. Provider billing limits remain separate."><Input type="number" min={0} max={100000} value={allowance} onChange={e=>setAllowance(Number(e.target.value))}/></Field></div><p className="mb-1 max-w-md text-sm leading-6 text-muted-foreground">Saving a connection authorizes this brand’s editors to use its remaining allowance. Keys remain visible only as connection names.</p></div>}
    {(["openai","anthropic","gemini","perplexity_api","xai"] as Provider[]).map(p=>{const own=saved.filter(c=>c.provider===p),grant=grants.find(g=>g.id===value[p].connectionId);return <section key={p} className="rounded-xl border bg-white p-6"><div className="mb-5 flex flex-wrap items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-secondary font-semibold">{providerNames[p].slice(0,1)}</span><div className="flex-1"><h2 className="font-semibold">{providerNames[p]}</h2><p className="mt-1 text-sm text-muted-foreground">{p==="openai"?"Responses API + web search":p==="anthropic"?"Messages API + web search":p==="gemini"?"Interactions API + Google Search":p==="xai"?"Responses API + web search":"Sonar API · citations and search results"}</p></div><Status value={value[p].connectionId?"saved":value[p].key?"tab_only":"not_connected"}/></div>
      {(own.length>0||grants.some(g=>g.provider===p))&&<div className="mb-4"><Choice label={`${providerNames[p]} saved connection`} value={value[p].connectionId||"temporary"} onChange={id=>{const c=[...own,...grants].find(c=>c.id===id);update(p,{connectionId:c?.id,model:c?.model||value[p].model,key:"",checked:false});}} options={[["temporary","Temporary key / new connection"],...Array.from(new Map([...own,...grants.filter(g=>g.provider===p)].map(c=>[c.id,c])).values()).map(c=>[c.id,c.label] as [string,string])]}/></div>}
      <div className="grid gap-4 sm:grid-cols-2"><Field label={`${providerNames[p]} API key`} hint={value[p].connectionId?"Leave blank to retain the saved credential.":"Temporary until you choose Save securely."}><Input type="password" autoComplete="off" spellCheck={false} value={value[p].key} disabled={!enabled||!!busy||!!value[p].connectionId&&!own.some(c=>c.id===value[p].connectionId)} onChange={e=>update(p,{key:e.target.value,checked:false})} placeholder={value[p].connectionId?"Saved credential":"Paste API key"}/></Field><Field label="Model ID"><Input list={`models-${p}`} value={value[p].model} disabled={!enabled||!!busy} onChange={e=>update(p,{model:e.target.value})} placeholder="Choose or enter a model ID"/></Field></div><datalist id={`models-${p}`}>{value[p].models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist>
      {grant&&<div className="mt-4 flex flex-wrap items-center gap-4 rounded-lg bg-secondary/50 p-3 text-sm"><span>{grant.used_requests} / {grant.request_limit} authorized requests used</span>{owner&&<form className="flex items-center gap-2" onSubmit={e=>{e.preventDefault();const n=Number(new FormData(e.currentTarget).get("limit"));void perform(p,async()=>{await workspaceApi("grant_connection",{studyId:study!.id,connectionId:grant.id,requestLimit:n});});}}><Input className="w-28" name="limit" aria-label="Total request allowance" type="number" min={grant.used_requests} max={100000} defaultValue={grant.request_limit}/><Button size="sm" variant="outline" disabled={!!busy}>Update allowance</Button></form>}</div>}
      {value[p].checked&&<p className="mt-3 text-sm text-emerald-800">{value[p].models.length} models returned. Model access does not guarantee search-tool compatibility.</p>}
      <div className="mt-5 flex flex-wrap gap-3"><Button variant="outline" disabled={!enabled||p==="perplexity_api"||!!busy||(!value[p].key&&!own.some(c=>c.id===value[p].connectionId))} onClick={()=>check(p)}>{busy===p&&<Loader2 className="animate-spin" size={14}/>}Check key & models</Button><Button disabled={!enabled||!!busy||!vault||(!value[p].key&&!own.some(c=>c.id===value[p].connectionId))||!value[p].model} onClick={()=>save(p)}>Save securely</Button>{own.some(c=>c.id===value[p].connectionId)&&<Button variant="ghost" disabled={!!busy} onClick={()=>perform(p,async()=>{await workspaceApi("disconnect",{id:value[p].connectionId});update(p,{connectionId:undefined,key:"",checked:false});})}><Unplug size={14}/>Disconnect</Button>}<a href={urls[p]} target="_blank" rel="noopener noreferrer" className="ml-auto inline-flex items-center gap-1 text-sm text-primary">Get an API key<ExternalLink size={13}/></a></div>
    </section>;})}
    {owner&&<section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Background execution</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">Connect an Upstash QStash account to deliver jobs and scheduled studies while the browser is closed. The queue receives job IDs and scoped delivery tokens; provider keys and brand prompts remain here. A plan supporting 180-second delivery is required.</p><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_auto]"><Field label="QStash token · EU Central endpoint"><Input type="password" autoComplete="off" value={queueKey} onChange={e=>setQueueKey(e.target.value)} placeholder={saved.some(c=>c.provider==="qstash")?"Connection saved; enter token to replace":"Paste QStash token"}/></Field><Button className="sm:mt-6" disabled={!enabled||!vault||!queueKey||!!busy} onClick={()=>perform("queue",async()=>{await workspaceApi("connection",{id:saved.find(c=>c.provider==="qstash")?.id,provider:"qstash",label:"Background queue",model:"",key:queueKey});setQueueKey("");})}>Save queue connection</Button></div><div className="mt-4 flex flex-wrap items-center gap-3"><Status value={saved.some(c=>c.provider==="qstash")?"saved":"not_connected"}/>{study&&<Button variant="outline" disabled={!enabled||!!busy} onClick={()=>perform("probe",async()=>{const result=await monitorApi("probe",{studyId:study.id});setProbe(result.reachable?"Callback reachable. Queue delivery still needs a successful test run.":"The site’s access gate blocks external delivery. The operator must enable callback access before unattended collection.");})}>Check callback access</Button>}<a href="https://console.upstash.com/qstash" target="_blank" rel="noopener noreferrer" className="text-sm text-primary">Open QStash<ExternalLink size={13} className="ml-1 inline"/></a></div>{probe&&<p role="status" className="mt-4 text-sm leading-6">{probe}</p>}</section>}
    <Note>Consumer subscriptions do not include provider API billing. API responses are not a reproduction of a signed-in customer’s ChatGPT, Claude, or Google experience.</Note>
  </div>;
}
