'use client';
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, ErrorMessage } from './workflow-ui';
import { Choice, Field, Note, Status } from './ui';
import { investigationApi, readFrom } from '@/lib/client';
import { coverageBoard, surfaces, summarizeRun, type CoverageCell, type ObservationSummary } from '@/lib/investigation';
import type { Study, Run, ResearchRecord } from '@/lib/research';
type Board=ReturnType<typeof coverageBoard>;
export function Coverage({study,records,runs,enabled,demo,onOpen,onCapture,onPlan,onRefresh}:{study:Study;records:ResearchRecord[];runs:Run[];enabled:boolean;demo:boolean;onOpen:(id:string)=>void;onCapture:(prompt:string,mode:string,targetId:string)=>void;onPlan:()=>void;onRefresh:()=>Promise<void>}){
 const questions=records.filter(r=>r.kind==='question');const [loading,setLoading]=useState(!demo),[board,setBoard]=useState<Board>({cells:[],unassigned:[],total:0}),[question,setQuestion]=useState(questions[0]?.id||''),[surface,setSurface]=useState('consumer:chatgpt'),[expected,setExpected]=useState(2),[filter,setFilter]=useState('all'),[context,setContext]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[assignment,setAssignment]=useState(''),[unassignedPage,setUnassignedPage]=useState(0);
 async function refresh(){if(demo){setBoard(coverageBoard(records,runs.map(summarizeRun)));return;}const data=await readFrom('investigation','coverage',{studyId:study.id});setBoard(data);}
 useEffect(()=>{let active=true;setLoading(!demo);if(demo){setBoard(coverageBoard(records,runs.map(summarizeRun)));return;}void readFrom('investigation','coverage',{studyId:study.id}).then(data=>{if(active)setBoard(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[study.id,records,runs.length,demo]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await investigationApi('coverage',{studyId:study.id,questionId:question,surface,expected});await onRefresh();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function changeExpected(cell:CoverageCell,value:number){setBusy(true);setError('');try{await investigationApi('coverage',{studyId:study.id,id:cell.id,questionId:cell.questionId,surface:cell.surface,expected:value,expectedUpdatedAt:cell.updatedAt});await onRefresh();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const cell=board.cells.find(c=>c.id===selected);const cells=board.cells.filter(c=>(filter==='all'||c.surface.startsWith(filter+':'))&&`${c.prompt} ${JSON.stringify(c.context)}`.toLowerCase().includes(context.toLowerCase()));const rows=Array.from(new Set(cells.map(c=>`${c.questionId}:${c.questionVersion}`)));const columns=Array.from(new Set(cells.map(c=>c.surface)));
 async function assign(run:ObservationSummary){setBusy(true);setError('');try{await investigationApi('assign',{studyId:study.id,targetId:assignment,runId:run.id,expectedUpdatedAt:records.find(r=>r.kind==='assignment'&&r.payload.runId===run.id)?.updated_at});await onRefresh();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(loading)return <div role="status" className="rounded-xl border bg-white p-8 text-sm">Loading coverage across the complete study…</div>;
 return <div className="space-y-6"><ErrorMessage message={error}/><Card title="Every question. Every surface." description={`${board.total} observations across the complete study. Missing and failed records are research gaps, not negative brand findings.`}><div className="mb-5 grid gap-3 sm:grid-cols-2"><Choice label="Coverage collection method" value={filter} onChange={setFilter} options={[["all","All methods · separately counted"],["api","API"],["consumer","Consumer apps"],["imported","Imported API responses"]]}/><Input aria-label="Filter coverage context" placeholder="Filter question, market, product or audience…" value={context} onChange={e=>setContext(e.target.value)}/></div>{cells.length?<div className="max-w-full overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="min-w-56 p-4">Saved question & context</th>{columns.map(s=><th key={s} className="min-w-40 p-4">{surfaces.find(([id])=>id===s)?.[1]}<span className="mt-1 block font-normal text-muted-foreground">{s.split(':')[0]}</span></th>)}</tr></thead><tbody>{rows.map(key=>{const group=cells.filter(c=>`${c.questionId}:${c.questionVersion}`===key),first=group[0];return <tr key={key} className="border-t"><th className="max-w-80 p-4 font-normal"><p className="font-medium leading-6">{first.prompt}</p><p className="mt-2 text-xs text-muted-foreground">{['audience','market','language','purpose'].map(k=>String(first.context[k]||'')).filter(Boolean).join(' · ')||'Context not specified'}<br/>Question version: {first.questionVersion.slice(0,10)}</p></th>{columns.map(s=>{const c=group.find(c=>c.surface===s);return <td key={s} className="p-2 align-top">{c?<button onClick={()=>{setSelected(c.id);setAssignment(c.id);}} className={`w-full rounded-lg border p-3 text-left focus-visible:outline-2 focus-visible:outline-primary ${selected===c.id?'border-primary bg-blue-50':'hover:bg-slate-50'}`}><strong className="text-xl">{c.counts.complete}<span className="text-sm font-normal text-muted-foreground"> / {c.expected} complete</span></strong><span className="mt-2 block text-sm">{c.counts.missing} missing</span><span className="mt-2 block text-xs text-muted-foreground">{['queued','running','partial','failed','cancelled'].map(k=>`${c.counts[k]} ${k}`).join(' · ')}</span></button>:<span className="px-3 text-muted-foreground">Not planned</span>}</td>;})}</tr>;})}</tbody></table></div>:<Note>No targets in this view. Choose a saved question and a platform below to define the coverage you want.</Note>}</Card>
 {cell&&<Card title={surfaces.find(([id])=>id===cell.surface)?.[1]||cell.surface} description={cell.prompt}><div className="mb-4 flex flex-wrap items-end gap-3"><Field label="Expected repetitions"><Input aria-label="Update expected repetitions" type="number" min={1} max={20} defaultValue={cell.expected} key={cell.id+cell.updatedAt} onBlur={e=>{const n=Number(e.target.value);if(n!==cell.expected&&n>=1&&n<=20)void changeExpected(cell,n);}} disabled={!enabled||busy}/></Field><Button disabled={!enabled} onClick={()=>cell.surface.startsWith('api:')?onPlan():onCapture(cell.prompt,cell.surface.startsWith('consumer:')?'consumer':'import',cell.id)}>{cell.surface.startsWith('api:')?'Open collection planner':'Record or import observation'}</Button></div><Note>Assignments are explicit evidence organization. They do not establish identical personalization, location or search behavior.</Note><div className="mt-4 space-y-2">{cell.observations.map(r=><button key={r.id} onClick={()=>onOpen(r.id)} className="flex w-full flex-wrap items-center justify-between gap-3 rounded-lg border p-3 text-left hover:bg-slate-50"><span>{r.prompt}<span className="mt-1 block text-xs text-muted-foreground">{r.model} · {r.created_at}</span></span><Status value={r.status}/></button>)}</div></Card>}
 <Card title="Plan another observation"><form onSubmit={save} className="grid items-end gap-4 md:grid-cols-[2fr_1fr_100px_auto]"><Field label="Saved question"><Choice label="Coverage question" value={question} onChange={setQuestion} options={questions.map(q=>[q.id,q.payload.prompt])}/></Field><Field label="Exact platform & method"><Choice label="Coverage surface" value={surface} onChange={setSurface} options={surfaces.map(([a,b])=>[a,`${b} · ${a.split(':')[0]}`])}/></Field><Field label="Repetitions"><Input type="number" min={1} max={20} value={expected} onChange={e=>setExpected(Number(e.target.value))}/></Field><Button disabled={!enabled||busy||!question}>Add target</Button></form></Card>
 <Card title={`${board.unassigned.length} observations without a matching target`} description="Earlier and manually imported observations stay visible. Assigning one does not change its original question or recorded conditions."><Choice label="Assign observation to target" value={assignment} onChange={setAssignment} options={[["","Choose a target"],...board.cells.map(c=>[c.id,`${surfaces.find(([id])=>id===c.surface)?.[1]} · ${c.prompt}`] as [string,string])]}/><div className="mt-4 divide-y">{board.unassigned.slice(unassignedPage*20,(unassignedPage+1)*20).map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 py-4"><button className="min-w-0 flex-1 text-left text-sm font-medium hover:underline" onClick={()=>onOpen(r.id)}>{r.prompt}<span className="mt-1 block font-normal text-muted-foreground">{r.environment} · {r.provider} · {r.status}</span></button><Button variant="outline" size="sm" disabled={!enabled||busy||!board.cells.some(c=>c.id===assignment&&c.surface===`${r.environment}:${r.provider}`)} onClick={()=>assign(r)}>Assign to target</Button></div>)}</div>{board.unassigned.length>20&&<div className="mt-3 flex items-center gap-3"><Button variant="outline" disabled={!unassignedPage} onClick={()=>setUnassignedPage(p=>p-1)}>Previous</Button><span className="text-sm">Page {unassignedPage+1}</span><Button variant="outline" disabled={(unassignedPage+1)*20>=board.unassigned.length} onClick={()=>setUnassignedPage(p=>p+1)}>Next</Button></div>}</Card></div>;
}
