"use client";
import { useEffect, useState } from "react";
import { Copy, Link2, MessageSquareText, ShieldOff, Download } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { readResearch, researchApi, displayDate } from "@/lib/client";
import type { ResearchRecord, Run, Study } from "@/lib/research";
import { Choice, Field, Note } from "./ui";
import { ReportPage } from "./report";

export function Delivery({ study, runs, records, enabled, authenticated=enabled, demo=false }: { authenticated?:boolean; demo?:boolean; study: Study; runs: Run[]; records: ResearchRecord[]; enabled: boolean }) {
  const [reports, setReports] = useState<any[]>([]), [creating, setCreating] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [title, setTitle] = useState(`${study.brand} · Brand investigation`), [days, setDays] = useState("14"), [link, setLink] = useState("");
  const [inbox, setInbox] = useState<{ title: string; comments: any[] } | null>(null);
  async function refresh() { if (authenticated) { try { setReports((await readResearch("resources", { studyId: study.id })).reports); } catch (e) { setError((e as Error).message); } } }
  useEffect(() => { void refresh(); }, [study.id, authenticated]);
  async function create(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const data = await researchApi("snapshot", { studyId: study.id, title, runIds: runs.map(r => r.id), expiresInDays: Number(days) }); setLink(`${window.location.origin}${data.path}`); setCreating(false); await refresh(); toast.success("Dated report version created."); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function revoke(id: string) { try { await researchApi("revoke_report", { studyId: study.id, id }); setLink(""); await refresh(); toast.success("Report link revoked."); } catch (e) { toast.error((e as Error).message); } }
  async function comments(report: any) { try { const data = await readResearch("report_comments", { studyId: study.id, id: report.id }); setInbox({ title: report.title, comments: data.comments }); } catch (e) { toast.error((e as Error).message); } }
  return <div className="space-y-6"><section className="rounded-xl border bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-semibold">A report clients can question</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Preserve this scope as a dated version. Readers can attach questions to a finding; later edits in your workspace leave this version intact.</p></div><Button disabled={!enabled || !runs.length || runs.length > 100} onClick={() => setCreating(true)}><Link2 size={16}/>Create report link</Button></div><div className="mt-5"><Note>Report links work for people who can access this site. Each link also grants access to its selected answers and assessments until expiry or revocation. Site access must be arranged separately. Nothing is sent automatically.</Note></div>{runs.length > 100 && <p className="mt-3 text-sm text-amber-800">Narrow the scope to 100 observations or fewer to create a report link.</p>}{link && <div className="mt-5 rounded-lg border border-blue-200 bg-blue-50 p-4"><label htmlFor="new-report-link" className="text-sm font-semibold">Copy and keep this link — shown only in this session</label><div className="mt-3 flex gap-2"><Input id="new-report-link" readOnly value={link}/><Button variant="outline" onClick={async () => { try { await navigator.clipboard.writeText(link); toast.success("Report link copied."); } catch { toast.error("Select the link and copy it manually."); } }} aria-label="Copy report link"><Copy size={16}/></Button></div><a className="mt-3 inline-block text-sm text-primary underline" href={link} target="_blank" rel="noreferrer">Open report</a></div>}{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}{reports.length > 0 && <div className="mt-6 divide-y border-t">{reports.map(r => { const active = !r.revoked_at && new Date(r.expires_at).getTime() > Date.now(); return <div key={r.id} className="flex flex-wrap items-center gap-3 py-4"><div className="mr-auto"><p className="text-sm font-medium">{r.title}</p><p className="mt-1 text-xs text-muted-foreground">Created {displayDate(r.created_at)} · {r.revoked_at ? "Revoked" : active ? `Expires ${displayDate(r.expires_at)}` : "Expired"}</p></div><Button asChild size="sm" variant="outline"><a href={`/api/research?action=report_document&studyId=${study.id}&id=${r.id}`}><Download size={14}/>Download version</a></Button><Button size="sm" variant="ghost" onClick={() => comments(r)}><MessageSquareText size={14}/>Client questions</Button><Button size="sm" variant="outline" disabled={!enabled || !active} onClick={() => revoke(r.id)}><ShieldOff size={14}/>Revoke</Button></div>; })}</div>}</section><ReportPage study={study} runs={runs} records={records} demo={demo}/>
    <Dialog open={creating} onOpenChange={open => { if (!busy) setCreating(open); }}><DialogContent><DialogHeader><DialogTitle>Create a dated report link</DialogTitle><DialogDescription>This version includes {runs.length} observations in the current scope and their human assessments. Review the preview first.</DialogDescription></DialogHeader><form onSubmit={create} className="space-y-5"><Field label="Report title"><Input required maxLength={200} value={title} onChange={e => setTitle(e.target.value)}/></Field><Choice label="Expires after" value={days} onChange={setDays} options={[["1", "1 day"], ["7", "7 days"], ["14", "14 days"], ["30", "30 days"]]}/>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy} type="submit">{busy ? "Creating…" : "Create version and link"}</Button></form></DialogContent></Dialog>
    <Dialog open={!!inbox} onOpenChange={open => { if (!open) setInbox(null); }}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Client questions</DialogTitle><DialogDescription>{inbox?.title} · Names are supplied by readers and are not verified identities.</DialogDescription></DialogHeader>{inbox?.comments.length ? inbox.comments.map(c => <article key={c.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3 text-sm"><strong>{c.author}</strong><span className="text-muted-foreground">{displayDate(c.created_at)}</span></div>{c.review_id && <p className="mt-3 text-xs text-muted-foreground">Finding: {records.find(r => r.id === c.review_id)?.payload.claim || c.review_id}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6">{c.message}</p></article>) : <p className="py-5 text-sm text-muted-foreground">No reader questions yet.</p>}</DialogContent></Dialog>
  </div>;
}
