"use client";
import {Check,ArrowRight} from "lucide-react";
import {Button} from "@/components/ui/button";
import type {ResearchRecord,Run,Study} from "@/lib/research";
export function FirstInvestigation({study,records,runs,onNavigate}:{study:Study;records:ResearchRecord[];runs:Run[];onNavigate:(s:string)=>void}){
 const steps=[{label:"Define customer questions",detail:"Start with actual buying decisions and a repeatable research set.",page:"questions",done:records.some(r=>r.kind==="question")},{label:"Collect the first answers",detail:"Connect a provider account, or capture what a consumer app displayed.",page:"collect",done:runs.some(r=>r.status==="complete"||r.status==="manually_recorded")},{label:"Review a claim against evidence",detail:"Click a passage, inspect its source, and record your assessment.",page:"observations",done:records.some(r=>r.kind==="review")},{label:"Prepare the client’s report",detail:"Choose the evidence and create a dated, inspectable report.",page:"report",done:false}];
 if(records.some(r=>r.kind==="review"))return null;
 return <section className="mb-6 rounded-xl border border-blue-200 bg-blue-50/40 p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Your first investigation of {study.brand}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Each step leaves a saved record your client can inspect.</p></div><span className="text-xs text-muted-foreground">{steps.filter(s=>s.done).length} of 4</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{steps.map((s,i)=><button key={s.page} onClick={()=>onNavigate(s.page)} className="flex items-start gap-3 rounded-lg border bg-white p-4 text-left hover:border-primary"><span className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs ${s.done?"bg-emerald-50 text-emerald-700":"bg-secondary text-primary"}`}>{s.done?<Check size={14}/>:i+1}</span><span><span className="text-sm font-medium">{s.label}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{s.detail}</span></span><ArrowRight size={15} className="ml-auto mt-1 shrink-0 text-muted-foreground"/></button>)}</div></section>;
}
