"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Loader2 } from "lucide-react";
import { api } from "@/lib/client";
import type { SelectedClaim } from "@/lib/claims";
import type { ResearchRecord, Study } from "@/lib/research";
import { useSavedDraft } from "./workflow-ui";
import { Choice, Field } from "./ui";
type BaseProps = { onClose: () => void; onSaved: (id: string) => Promise<void> | void };
export function StudyForm({ study, onClose, onSaved }: BaseProps & { study?: Study }) {
  const [values, set] = useState({ name: study?.name || "", brand: study?.brand || "", website: study?.website || "", objective: study?.objective || "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const data = await api("study", { ...values, id: study?.id }); await onSaved(data.id); onClose(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog open onOpenChange={v => { if (!v && !busy) onClose(); }}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{study ? "Edit study" : "Start a research study"}</DialogTitle><DialogDescription>Give your brand research a question and a place to keep its evidence.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-5">
    <Field label="Study name"><Input required maxLength={120} placeholder="e.g. How customers discover Aster" value={values.name} onChange={e => set({ ...values, name: e.target.value })}/></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Brand or product"><Input required maxLength={120} placeholder="Brand name" value={values.brand} onChange={e => set({ ...values, brand: e.target.value })}/></Field><Field label="Brand website (optional)"><Input type="url" placeholder="https://" value={values.website} onChange={e => set({ ...values, website: e.target.value })}/></Field></div>
    <Field label="What are you trying to learn? (optional)"><Textarea rows={3} maxLength={4000} placeholder="Which product claims appear in answers, and what evidence supports them?" value={values.objective} onChange={e => set({ ...values, objective: e.target.value })}/></Field>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={busy}>Cancel</Button><Button disabled={busy}>{busy && <Loader2 className="animate-spin"/>}{study ? "Save changes" : "Create study"}</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}
export function RecordForm({ kind, record, selection, studyId, runId, facts = [], products = [], onClose, onSaved }: BaseProps & { kind: "fact" | "question" | "review"; record?: ResearchRecord; selection?: SelectedClaim; studyId: string; runId?: string; facts?: ResearchRecord[]; products?: ResearchRecord[] }) {
  const {value:v,setValue:set,status:draftStatus,clear:clearDraft,reload:reloadDraft,conflict:draftConflict}=useSavedDraft<any>(studyId,`record:${kind}:${record?.id||runId||"new"}:${record?.updated_at||selection?.start||0}`,record?.payload || (kind === "fact" ? { claim: "", product: "", source: "", excerpt: "", checkedAt: new Date().toISOString().slice(0, 10), status: "needs_review", notes: "" } : kind === "question" ? { prompt: "", intent: "discovery", origin: "researcher", tags: [], notes: "" } : { runId, claim: selection?.text || "", anchor: selection ? { segmentIndex: selection.segmentIndex, start: selection.start, end: selection.end } : null, impact: "", recommendation: "", verdict: "uncertain", evidenceLevel: "observed", materiality: "medium", factIds: [], explanation: "", hypothesis: "", nextTest: "" }));
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const update = (key: string, value: any) => set((old: any) => ({ ...old, [key]: value }));
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const data = await api("record", { id: record?.id, expectedUpdatedAt: record?.updated_at, kind, studyId, payload: v }); await clearDraft().catch(()=>{}); await onSaved(data.id); onClose(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const title = kind === "fact" ? "Product fact" : kind === "question" ? "Customer question" : "Claim review";
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{record ? "Edit" : "Add"} {title.toLowerCase()}</DialogTitle><DialogDescription>{kind === "fact" ? "Record a checkable fact and its supporting source. Your status is a human judgment." : kind === "question" ? "Use a question a customer might actually ask. Saved questions are reusable across providers." : "Review one claim or omission against evidence. Keep explanations and hypotheses distinct."}</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-5">
    {kind === "fact" && <><Field label="Fact or claim"><Textarea required rows={2} maxLength={4000} value={v.claim} onChange={e => update("claim", e.target.value)} placeholder="One specific, checkable product statement"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Product / version (optional)"><Input maxLength={300} value={v.product} onChange={e => update("product", e.target.value)}/></Field><Field label="Review status"><Choice value={v.status} onChange={x => update("status", x)} options={[["needs_review", "Needs review"], ["verified", "Verified by me"], ["disputed", "Disputed"]]}/></Field></div><Field label="Source URL"><Input required type="url" value={v.source} onChange={e => update("source", e.target.value)} placeholder="https://"/></Field><Field label="Supporting excerpt"><Textarea required rows={3} maxLength={8000} value={v.excerpt} onChange={e => update("excerpt", e.target.value)} placeholder="Paste the relevant source passage"/></Field><Field label="Date checked"><Input required type="date" value={v.checkedAt} onChange={e => update("checkedAt", e.target.value)}/></Field></>}
    {kind === "question" && <><Field label="Exact question"><Textarea required rows={4} maxLength={12000} value={v.prompt} onChange={e => update("prompt", e.target.value)} placeholder="What would a customer ask?"/></Field><Field label="Customer intent"><Choice value={v.intent} onChange={x => update("intent", x)} options={[["discovery", "Discovery"], ["comparison", "Comparison"], ["verification", "Fact verification"], ["purchase", "Purchase"], ["support", "Support"]]}/></Field><Field label="Question origin"><Choice value={v.origin || "researcher"} onChange={x => update("origin", x)} options={[["researcher", "Researcher scenario"], ["customer", "Actual customer question"], ["template", "Template"], ["ai_suggested", "AI suggestion"]]}/></Field></>}
    {kind!=="review"&&<Field label="Linked product or offer" hint="The product version is preserved with this record."><Choice value={v.productId||"none"} onChange={x=>update("productId",x==="none"?undefined:x)} options={[["none","Brand level · no specific product"],...products.map(p=>[p.id,`${p.payload.name}${p.payload.sku?` · ${p.payload.sku}`:""}`] as [string,string])]}/></Field>}
    {kind==="question"&&<details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Audience and research context</summary><p className="my-3 text-xs leading-6 text-muted-foreground">Context labels group your study. They do not silently change the exact prompt or emulate a consumer’s location.</p><div className="grid gap-4 sm:grid-cols-2">{[["audience","Audience"],["market","Market / geography"],["language","Language"]].map(([key,label])=><Field key={key} label={label}><Input maxLength={key==="audience"?300:100} value={v[key]||""} onChange={e=>update(key,e.target.value)}/></Field>)}</div></details>}
    {kind === "review" && <><Field label="Exact claim or expected information" hint={v.anchor ? "Linked to the original passage. Its exact text is preserved." : "To link an exact passage, close this form and click it in the answer."}><Textarea readOnly={!!v.anchor} required rows={3} maxLength={6000} value={v.claim} onChange={e => update("claim", e.target.value)} placeholder="Quote a claim, or describe information you expected to appear"/></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Verdict"><Choice value={v.verdict} onChange={x => update("verdict", x)} options={[["supported", "Supported"], ["contradicted", "Contradicted"], ["uncertain", "Uncertain"], ["omitted", "Omitted"]]}/></Field><Field label="Evidence level"><Choice value={v.evidenceLevel} onChange={x => update("evidenceLevel", x)} options={[["observed", "Observed"], ["inferred", "Inferred"], ["experimentally_supported", "Experiment supported"], ["unknown", "Unknown"]]}/></Field><Field label="Materiality"><Choice value={v.materiality} onChange={x => update("materiality", x)} options={[["low", "Low"], ["medium", "Medium"], ["high", "High"]]}/></Field></div>
      <div><div className="field-label">Reference facts and passages</div>{facts.length ? <div className="max-h-40 space-y-3 overflow-y-auto rounded-lg border p-3">{facts.map(f => <label key={f.id} className="flex cursor-pointer items-start gap-2.5 text-sm"><Checkbox className="mt-0.5" checked={v.factIds.includes(f.id)} onCheckedChange={checked => update("factIds", checked ? [...v.factIds, f.id] : v.factIds.filter((x: string) => x !== f.id))}/><span>{f.payload.claim}</span></label>)}</div> : <p className="text-sm text-muted-foreground">No product facts yet. You can add them and edit this review later.</p>}</div>
      <Field label="Evidence and reasoning"><Textarea required rows={3} maxLength={10000} value={v.explanation} onChange={e => update("explanation", e.target.value)} placeholder="What does the recorded evidence establish? Include source details."/></Field><Field label="Why this matters to the client (optional)"><Textarea rows={2} maxLength={4000} value={v.impact || ""} onChange={e => update("impact", e.target.value)} placeholder="Which customer decision or brand perception could this affect?"/></Field><Field label="Recommended action (optional)"><Textarea rows={3} maxLength={8000} value={v.recommendation || ""} onChange={e => update("recommendation", e.target.value)} placeholder="Specify a useful action and the evidence that would show whether it worked."/></Field><Field label="Hypothesis (optional)"><Textarea rows={2} maxLength={8000} value={v.hypothesis} onChange={e => update("hypothesis", e.target.value)} placeholder="A possible explanation, not a proven internal cause"/></Field><Field label="Next test (optional)"><Textarea rows={2} maxLength={8000} value={v.nextTest} onChange={e => update("nextTest", e.target.value)} placeholder="What controlled change would help test this explanation?"/></Field></>}
    {kind !== "review" && <Field label="Notes (optional)"><Textarea rows={2} maxLength={4000} value={v.notes} onChange={e => update("notes", e.target.value)}/></Field>}
    <p role="status" className="text-xs text-muted-foreground">{draftStatus}</p>{draftConflict&&<Button type="button" variant="outline" onClick={reloadDraft}>Reload saved draft</Button>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={busy}>Cancel</Button><Button disabled={busy}>{busy && <Loader2 className="animate-spin"/>}Save {title.toLowerCase()}</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}
