"use client";
import { Fragment, useEffect, useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ArrowUpRight, Check, Download, FileText, GitBranch, Link2, Loader2, Plus, Search, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { displayDate, download, readApi } from "@/lib/client";
import { domainOf, environments, providerNames, type ResearchRecord, type Run } from "@/lib/research";
import { Field, Note, SourceLink, Status } from "./ui";
import { citationSpan, passages, reviewFacts, type SelectedClaim } from "@/lib/claims";
import { ClaimPanel } from "./claim-panel";
const roleNames: Record<string, string> = { cited: "Cited in answer", provider_disclosed_consulted: "Disclosed as consulted", provider_disclosed_search_result: "Returned search result", open_page_target: "Open-page target", manually_recorded_link: "Link recorded by observer" };
function googleSuggestions(run: Run) {
  if (run.provider !== "gemini") return [];
  const result: string[] = [];
  function walk(value: any, depth = 0) {
    if (!value || typeof value !== "object" || depth > 20) return;
    if (Array.isArray(value)) { value.forEach(x => walk(x, depth + 1)); return; }
    for (const [key, v] of Object.entries(value)) {
      if (key === "search_suggestions" && typeof v === "string") result.push(v);
      else if (key === "search_suggestions" && v && typeof v === "object" && "rendered_content" in v && typeof v.rendered_content === "string") result.push(v.rendered_content);
      else walk(v, depth + 1);
    }
  }
  run.normalized?.tool_events.forEach(x => walk(x.native)); return result;
}
export function Inspector({ run, records, demo, onReview, onEditReview, onRefresh, onRepeat }: { run: Run; records: ResearchRecord[]; demo: boolean; onReview: (claim?: SelectedClaim) => void; onEditReview: (r: ResearchRecord) => void; onRefresh: () => Promise<void>; onRepeat: () => void }) {
  const [claim, setClaim] = useState<SelectedClaim | null>(null);
  const [tab, setTab] = useState("answer"); const [original, setOriginal] = useState<any>(null); const [rawBusy, setRawBusy] = useState(false); const [uploading, setUploading] = useState(false);
  useEffect(() => { setOriginal(null); setTab("answer"); setClaim(null); }, [run.id]);
  const data = run.normalized; const reviews = records.filter(x => x.kind === "review" && x.payload.runId === run.id);
  const sourceGroups = new Map<string, { title: string; roles: Set<string>; paths: string[] }>();
  data?.sources.forEach(s => { const entry = sourceGroups.get(s.url) || { title: s.title || domainOf(s.url), roles: new Set<string>(), paths: [] }; entry.roles.add(s.role); entry.paths.push(s.raw_path); sourceGroups.set(s.url, entry); });
  async function loadOriginal(save = false) {
    setRawBusy(true); try { const value = original || await readApi("evidence", { id: run.id }); setOriginal(value); if (save) download(value, `original-${run.id}.json`, false); } catch (e) { toast.error((e as Error).message); } finally { setRawBusy(false); }
  }
  async function upload(file?: File) {
    if (!file) return; if (file.size > 5_000_000) { toast.error("Choose a file smaller than 5 MB."); return; }
    setUploading(true); try { const form = new FormData(); form.append("runId", run.id); form.append("file", file); const res = await fetch("/api/evidence", { method: "POST", body: form }); const v: any = await res.json(); if (!res.ok) throw new Error(v.error); await onRefresh(); toast.success("Evidence file attached."); } catch (e) { toast.error((e as Error).message); } finally { setUploading(false); }
  }
  return <article className="min-w-0 bg-white">
    <div className="border-b px-5 py-5 lg:px-7"><div className="mb-3 flex flex-wrap items-center gap-2"><Badge variant="outline" className="rounded-md bg-slate-50 font-normal">{environments[run.environment] || run.environment}</Badge><Status value={run.status}/>{demo && <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-800">Synthetic example</Badge>}<span className="ml-auto text-xs text-muted-foreground">{displayDate(run.created_at)}</span></div><h2 className="text-lg font-semibold leading-7 tracking-tight">{run.prompt}</h2><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">{providerNames[run.provider]}<span className="mx-2">/</span>{run.model}</p><Button size="sm" variant="ghost" onClick={onRepeat} disabled={demo}><ArrowUpRight size={14}/>Use question again</Button></div></div>
    {run.error && <div role="alert" className="m-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{run.error}</div>}
    {run.status === "running" && <div className="m-5"><Note warning>This run has no final response yet. If the original request window closed, its completion and billing status may be unknown. Refresh before starting another request.</Note></div>}
    <Tabs value={tab} onValueChange={setTab} className="gap-0"><div className="overflow-x-auto overflow-y-hidden border-b px-5 lg:px-7"><TabsList variant="line" className="h-12 min-w-max gap-4"><TabsTrigger value="answer"><FileText size={14}/>Answer</TabsTrigger><TabsTrigger value="sources"><Link2 size={14}/>Sources <span className="text-xs text-muted-foreground">{sourceGroups.size}</span></TabsTrigger><TabsTrigger value="trace"><GitBranch size={14}/>Search trace</TabsTrigger><TabsTrigger value="reviews"><ShieldCheck size={14}/>Reviews <span className="text-xs text-muted-foreground">{reviews.length}</span></TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger></TabsList></div>
      <TabsContent value="answer" className="space-y-6 p-5 lg:p-7">
        <div className="rounded-lg border border-blue-100 bg-blue-50/60 px-4 py-3 text-sm text-blue-900">Click any sentence to inspect its citations, reference passages, and reviews.</div>
        {data?.warnings.map((warning, i) => <Note key={i} warning>{warning}</Note>)}
        {data?.segments.length ? data.segments.map((segment, index) => <div key={index} className="space-y-3"><p className="evidence-text text-base text-slate-700">{passages(segment.text, index).map((part, p) => <Fragment key={part.start}>{part.text.trim() ? <button type="button" className="inline rounded text-left hover:bg-blue-50 hover:underline decoration-blue-300 underline-offset-4 focus-visible:outline-2 focus-visible:outline-primary" aria-label={`Investigate passage ${index + 1}.${p + 1}: ${part.text.slice(0, 80)}`} onClick={() => setClaim(part)}>{part.text}</button> : part.text}{data.citations.filter(c => { const span = citationSpan(run, c); return c.segment_index === index && span && span.end > part.start && span.end <= part.end; }).map((c, n) => <sup key={n} className="mx-1 text-xs"><SourceLink url={c.native.url || ""} title={`[${data.citations.indexOf(c) + 1}]`}/></sup>)}</Fragment>)}</p>{data.citations.filter(c => c.segment_index === index).length > 0 && <div className="flex flex-wrap gap-2 border-t border-dashed pt-3">{data.citations.filter(c => c.segment_index === index).map((citation, i) => <span key={i} className="rounded-md border bg-slate-50 px-2 py-1 text-xs"><SourceLink url={citation.native.url || ""} title={citation.native.title || `Source ${i + 1}`}/></span>)}</div>}<p className="font-mono text-[10px] text-slate-400">{segment.raw_path}</p></div>) : <div className="py-8 text-sm text-muted-foreground">No answer text is available for this record. Check the original evidence and completion status.</div>}
        {googleSuggestions(run).map((html, i) => <iframe key={i} title={`Google search suggestions ${i + 1}`} className="h-40 w-full rounded-md border" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerPolicy="no-referrer" srcDoc={`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src https: data:; base-uri 'none'; form-action 'none'"><base target="_blank">${html}`}/>)}
        <div className="flex items-center justify-between gap-4 border-t pt-5"><p className="max-w-sm text-xs leading-5 text-muted-foreground">Citations show disclosed attribution. They do not establish that a claim is correct.</p><Button size="sm" variant="outline" disabled={demo || !data?.segments.length} onClick={() => onReview()}><Plus size={14}/>Review a claim</Button></div>
      </TabsContent>
      <TabsContent value="sources" className="space-y-5 p-5 lg:p-7"><Note>Source roles are different kinds of evidence. A returned search result is not proof that its contents influenced the answer. Pages missing here were not necessarily rejected.</Note>{sourceGroups.size ? <div className="space-y-4">{Array.from(sourceGroups).map(([url, s], index) => <div key={url} className="rounded-lg border p-4"><div className="flex gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-md bg-slate-100 text-xs font-semibold text-slate-500">{index + 1}</span><div className="min-w-0 flex-1"><div className="text-sm font-semibold"><SourceLink url={url} title={s.title}/></div><p className="mt-1 break-all text-xs text-muted-foreground">{url}</p><div className="mt-3 flex flex-wrap gap-1.5">{Array.from(s.roles).map(role => <Badge key={role} variant="secondary" className="rounded font-normal">{roleNames[role] || role}</Badge>)}</div><details className="mt-3 text-xs text-muted-foreground"><summary className="cursor-pointer">Locations in original response</summary><div className="mt-2 space-y-1 font-mono">{s.paths.map((path, n) => <p key={n} className="break-all">{path}</p>)}</div></details></div></div></div>)}</div> : <p className="py-8 text-sm text-muted-foreground">No source URLs were disclosed or recorded. This does not prove the model used no outside information.</p>}
        {!!data?.citations.length && <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Native citation metadata · {data.citations.length}</summary><p className="my-3 text-xs text-muted-foreground">Offsets and provider identifiers are retained as supplied.</p><pre className="raw-json max-h-96 overflow-auto rounded bg-slate-50 p-3">{JSON.stringify(data.citations, null, 2)}</pre></details>}
      </TabsContent>
      <TabsContent value="trace" className="space-y-5 p-5 lg:p-7"><Note>Only provider-disclosed tool events appear here. Private ranking decisions, complete internal context, and the set of rejected sources are unknown.</Note><div className="flex items-center gap-2 text-xs text-muted-foreground"><Search size={14}/>Search observation: <span className="font-medium text-foreground">{data?.search_observation.replaceAll("_", " ") || "not available"}</span></div>{data?.tool_events.length ? <ol className="space-y-4">{data.tool_events.map((event, i) => <li key={i} className="relative ml-3 border-l-2 border-blue-100 pb-1 pl-6"><span className="absolute -left-[13px] top-0 flex size-6 items-center justify-center rounded-full border border-blue-200 bg-white text-[10px] font-semibold text-primary">{i + 1}</span><p className="text-sm font-semibold">{String(event.native.name || event.native.type || "Disclosed event").replaceAll("_", " ")}</p><p className="mt-1 break-all font-mono text-[10px] text-muted-foreground">{event.raw_path}</p><pre className="raw-json mt-3 max-h-64 overflow-auto rounded-lg border bg-slate-50 p-3">{JSON.stringify(event.native, null, 2)}</pre></li>)}</ol> : <p className="py-6 text-sm text-muted-foreground">No machine-readable search events are available for this run.</p>}</TabsContent>
      <TabsContent value="reviews" className="space-y-5 p-5 lg:p-7"><div className="flex items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Human assessments against recorded evidence.</p><Button size="sm" onClick={() => onReview()} disabled={demo}><Plus size={14}/>Add review</Button></div>{reviews.length ? reviews.map(review => <div key={review.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center gap-2"><Status value={review.payload.verdict}/><Badge variant="outline" className="font-normal">{review.payload.evidenceLevel.replaceAll("_", " ")}</Badge><span className="text-xs text-muted-foreground">{review.payload.materiality} materiality</span><Button className="ml-auto" size="sm" variant="ghost" disabled={demo} onClick={() => onEditReview(review)}>Edit</Button></div><p className="text-sm font-semibold">{review.payload.claim}</p><p className="evidence-text text-sm text-slate-600">{review.payload.explanation}</p>{reviewFacts(review, records).map(fact => { return fact ? <div key={fact.id} className="flex gap-2 rounded bg-slate-50 p-2 text-xs"><Check size={13} className="mt-0.5 shrink-0"/><div>{fact.payload.claim}<br/><SourceLink url={fact.payload.source} title="Supporting source"/></div></div> : null; })}{review.payload.hypothesis && <div className="border-t pt-3 text-xs leading-5"><strong>Hypothesis</strong><p className="mt-1 text-muted-foreground">{review.payload.hypothesis}</p></div>}{review.payload.nextTest && <div className="text-xs leading-5"><strong>Next test</strong><p className="mt-1 text-muted-foreground">{review.payload.nextTest}</p></div>}</div>) : <div className="rounded-lg border border-dashed px-5 py-10 text-center"><ShieldCheck className="mx-auto mb-3 text-slate-300" size={30}/><p className="text-sm font-medium">No claims reviewed yet</p><p className="mt-2 text-xs text-muted-foreground">Start with one factual claim that could change a purchase decision.</p></div>}</TabsContent>
      <TabsContent value="evidence" className="space-y-6 p-5 lg:p-7"><div><h3 className="mb-3 text-sm font-semibold">Run conditions</h3><Table><TableBody>{[["Environment", environments[run.environment]], ["Provider", providerNames[run.provider]], ["Requested / reported model", run.model], ["Model in response", data?.model_reported || "Not disclosed"], ["Recorded", new Date(run.created_at).toISOString()], ["Search setting", run.search], ["Provider status", data?.native_status || "Not disclosed"], ["Parser", data?.parser_version || "Not available"]].map(([label, value]) => <TableRow key={label}><TableCell className="w-48 text-xs text-muted-foreground">{label}</TableCell><TableCell className="break-all text-xs">{value}</TableCell></TableRow>)}</TableBody></Table><details className="mt-3 text-xs"><summary className="cursor-pointer font-medium">All settings and provider usage</summary><pre className="raw-json mt-3 rounded bg-slate-50 p-3">{JSON.stringify({ settings: run.settings, usage: data?.usage }, null, 2)}</pre></details></div>
        <div className="space-y-3 border-t pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-sm font-semibold">Original record</h3><div className="flex gap-2"><Button variant="outline" size="sm" disabled={demo || rawBusy || !run.evidence_hash} onClick={() => loadOriginal()}>{rawBusy ? <Loader2 size={14} className="animate-spin"/> : <FileText size={14}/>}Inspect JSON</Button><Button variant="outline" size="sm" disabled={demo || rawBusy || !run.evidence_hash} onClick={() => loadOriginal(true)} aria-label="Download original record"><Download size={14}/></Button></div></div><p className="text-xs leading-5 text-muted-foreground">The original request and response are preserved for API runs. Imports and manual observations retain their supplied records. SHA-256 detects later file changes; it does not verify an imported record’s origin.</p>{run.evidence_hash && <p className="break-all rounded bg-slate-50 p-2 font-mono text-[10px] text-muted-foreground">SHA-256 · {run.evidence_hash}</p>}{original && <pre className="raw-json max-h-[500px] overflow-auto rounded-lg border bg-slate-50 p-4">{JSON.stringify(original, null, 2)}</pre>}</div>
        <div className="space-y-3 border-t pt-5"><h3 className="text-sm font-semibold">Screenshots & supporting files</h3>{run.attachments?.map(file => <a key={file.id} className="flex items-center gap-3 rounded-lg border p-3 text-sm hover:bg-slate-50" href={`/api/evidence?id=${file.id}`}><FileText size={17} className="text-muted-foreground"/><span className="min-w-0 flex-1 truncate">{file.name}</span><Download size={14}/></a>)}<Field label={uploading ? "Uploading evidence…" : "Attach a file"} hint="PNG, JPEG, PDF, text, or JSON · up to 5 MB. Files are saved with a content hash."><Input type="file" disabled={demo || uploading} accept=".png,.jpg,.jpeg,.pdf,.txt,.json" onChange={e => { void upload(e.target.files?.[0]); e.target.value = ""; }}/></Field></div>
      </TabsContent>
    </Tabs>
    <ClaimPanel claim={claim} run={run} records={records} demo={demo} onClose={() => setClaim(null)} onReview={onReview} onEditReview={onEditReview}/>
  </article>;
}
