"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowRight, ChartNoAxesCombined, Fingerprint, MessageSquareText, ShieldCheck } from "lucide-react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { readFrom } from "@/lib/client";
import type { Scope } from "@/lib/analytics";
import { measure, profileOf, reviewedThemes } from "@/lib/analytics";
import { answerOf, environments, providerNames, type Run, type Study, type ResearchRecord } from "@/lib/research";
import { Status } from "./ui";
export function Overview({ study, runs, records, onOpen, onNavigate, onCollect, onProfile, scope, authenticated=false }: { scope?:Scope; authenticated?:boolean; study: Study; runs: Run[]; records: ResearchRecord[]; onOpen: (id: string) => void; onNavigate: (v: string) => void; onCollect: () => void; onProfile: () => void }) {
  const localMetrics = useMemo(() => measure(study, runs, records), [study, runs, records]);
  const [remote,setRemote]=useState<{key:string;metrics:ReturnType<typeof measure>}|null>(null),[metricError,setMetricError]=useState("");
  const scopeKey=JSON.stringify({studyId:study.id,...scope,revision:runs.map(r=>`${r.id}:${r.status}`).join(","),reviewRevision:records.map(r=>r.updated_at).sort().at(-1)});
  useEffect(()=>{if(!authenticated||!scope)return;let active=true;setMetricError("");const timer=setTimeout(()=>{readFrom("explore","metrics",{studyId:study.id,...scope}).then(data=>{if(active)setRemote({key:scopeKey,metrics:data.metrics});}).catch(e=>{if(active)setMetricError(e.message);});},250);return()=>{active=false;clearTimeout(timer);};},[scopeKey,authenticated]);
  const metrics=authenticated&&remote?.key===scopeKey?remote.metrics:localMetrics,metricRuns=[...metrics.eligible,...metrics.excluded];
  const [shown,setShown]=useState(50);
  const [inspect, setInspect] = useState<{ title: string; ids: string[]; explanation: string } | null>(null);
  const own = metrics.brands[0], profile = profileOf(study), ids = new Set(metricRuns.map(r => r.id));
  const analysis = records.find(r => r.kind === "analysis" && r.payload.status !== "failed" && r.payload.inputRunIds?.every((id: string) => ids.has(id)));
  const theme=reviewedThemes(analysis,records)[0];
  const openReviews = metrics.reviews.filter(r => ["contradicted", "uncertain", "mixed", "context_dependent"].includes(r.payload.verdict));
  const show = (title: string, ids: string[], explanation: string) => {setShown(50);setInspect({ title, ids, explanation });};
  const rate = (v: number | null) => v === null ? "—" : `${Math.round(v)}%`
// A rate at small n is close to meaningless on its own; show the range it could plausibly be.
const withInterval = (v: number | null, interval: { low: number; high: number } | null) =>
  v === null ? "—" : interval ? `${Math.round(v)}% (95% CI ${Math.round(interval.low)}–${Math.round(interval.high)})` : `${Math.round(v)}%`;
  return <div className="space-y-6">
    {authenticated&&<p role="status" className={`rounded-lg border px-4 py-3 text-sm ${metricError?"border-amber-200 bg-amber-50":"bg-white text-muted-foreground"}`}>{metricError?`Complete-study metrics could not load: ${metricError} Displaying the loaded subset below.`:remote?.key===scopeKey?`Complete study · ${metrics.eligible.length+metrics.excluded.length} ${metrics.eligible.length+metrics.excluded.length===1?"observation matches":"observations match"} this scope. Every metric links to its contributing records.`:"Calculating complete-study metrics… The loaded sample is shown until calculation finishes."}</p>}
    <section className="grid overflow-hidden rounded-2xl border bg-white lg:grid-cols-[1.6fr_1fr]"><div className="p-6 sm:p-8"><div className="mb-5 flex items-center gap-2 text-sm text-primary"><Fingerprint size={17}/>The observed brand</div><h2 className="max-w-2xl font-serif text-3xl leading-tight tracking-tight sm:text-4xl">{theme ? theme.title : metrics.eligible.length ? `${study.brand}, through the answers.` : "Your brand has a story. Let's see which one AI tells."}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{theme ? theme.description : metrics.eligible.length ? `${own.mentions} of ${own.denominator} completed observations mention ${study.brand}. Explore the language and evidence behind those appearances.` : "Set your questions, collect observations, and build an evidence record you can return to."}</p><div className="mt-6 flex flex-wrap items-center gap-3"><Button onClick={() => metrics.eligible.length ? onNavigate("narrative") : onCollect()}>{metrics.eligible.length ? "Investigate the narrative" : "Plan your first collection"}<ArrowRight size={16}/></Button>{theme && <span className="text-xs text-muted-foreground">{theme.review?"Human-reviewed interpretation":"AI-assisted interpretation · Needs review"}</span>}</div></div><div className="border-t bg-[#f2f5ff] p-6 sm:p-8 lg:border-l lg:border-t-0"><p className="text-sm font-medium">Your intended positioning</p><p className="mt-3 text-sm leading-7 text-muted-foreground">{profile.positioning || "Add the qualities and buyer situations you want the brand to be known for."}</p><div className="mt-5 space-y-2 text-sm"><p><span className="text-muted-foreground">Category</span><br/>{profile.category || "Not specified"}</p><p><span className="text-muted-foreground">Audience</span><br/>{profile.audience || "Not specified"}</p></div><Button className="mt-5 px-0 text-primary" variant="link" onClick={onProfile}>Edit brand context<ArrowRight size={14}/></Button></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      { title: "Brand presence", value: withInterval(own.rate, own.interval), detail: `${own.mentions} / ${own.denominator} completed answers`, icon: ChartNoAxesCombined, action: () => show("Answers mentioning your brand", own.runIds, "Case-insensitive name and alias matching with word boundaries. This measures mentions, not endorsement or recommendation.") },
      { title: "Tracked share of voice", value: rate(own.share), detail: `${metrics.brands.length} configured brands`, icon: MessageSquareText, action: () => show("Tracked brand appearances", metrics.eligible.map(r => r.id), "Each configured brand counts at most once per answer. Denominator: total appearances of configured brands. It does not measure the entire market.") },
      { title: "Questions observed", value: String(metrics.promptCount), detail: `${metrics.eligible.length} eligible observations`, icon: Fingerprint, action: () => show("Research coverage", metrics.eligible.map(r => r.id), "Distinct exact question texts among completed answers. Repeated runs remain separate observations, not independent customers.") },
      { title: "Claims needing attention", value: String(openReviews.length), detail: `${metrics.reviews.length} human assessments`, icon: ShieldCheck, action: () => onNavigate("decisions") },
    ].map(card => <button key={card.title} onClick={card.action} className="group rounded-xl border bg-white p-5 text-left transition-colors hover:border-primary/40 focus-visible:outline-2 focus-visible:outline-primary"><div className="flex items-center justify-between text-sm text-muted-foreground">{card.title}<card.icon size={17}/></div><p className="mb-1 mt-5 text-3xl font-semibold tracking-tight tabular-nums">{card.value}</p><div className="flex items-center justify-between text-xs text-muted-foreground">{card.detail}<ArrowDownRight size={15} className="text-primary"/></div></button>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><section className="rounded-xl border bg-white p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-base font-semibold">Presence over time</h2><p className="mt-1 text-sm text-muted-foreground">Share of completed answers mentioning your brand</p></div></div>{metrics.days.length > 1 ? <div className="h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={metrics.days} margin={{ top: 8, right: 12, bottom: 4, left: -22 }}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e4e9f2"/><XAxis dataKey="date" tickFormatter={d => d.slice(5)} axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: "#61708a" }}/><YAxis domain={[0, 100]} tickFormatter={n => `${n}%`} axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: "#61708a" }}/><Tooltip formatter={(v: any) => [`${Number(v).toFixed(1)}%`, "Brand presence"]}/><Line type="linear" dataKey="rate" stroke="#3155d9" strokeWidth={2.5} dot={{ r: 3, fill: "#3155d9" }} isAnimationActive={false}/></LineChart></ResponsiveContainer></div> : <div className="flex h-56 flex-col items-center justify-center rounded-lg bg-muted/50 text-center"><ChartNoAxesCombined size={28} className="text-muted-foreground"/><p className="mt-3 text-sm font-medium">A trend needs more than one day.</p><p className="mt-1 text-sm text-muted-foreground">Repeat comparable questions to build a history.</p></div>}<p className="mt-4 text-xs leading-5 text-muted-foreground">Daily samples may contain different questions or conditions. A movement is an observation, not proof of a cause.</p></section>
    <section className="rounded-xl border bg-white p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold">The competitive picture</h2><Button size="sm" variant="ghost" onClick={onProfile}>Edit brands</Button></div><Table><TableHeader><TableRow><TableHead>Brand</TableHead><TableHead>Presence</TableHead><TableHead className="text-right">Answers</TableHead></TableRow></TableHeader><TableBody>{[...metrics.brands].sort((a, b) => b.mentions - a.mentions).map(b => <TableRow key={b.name}><TableCell className="font-medium"><button onClick={() => show(`${b.name} · appearances`, b.runIds, `Matched against this brand's configured name and aliases. Review individual passages for ambiguous names.`)} className="text-left hover:text-primary">{b.name}{b.own && <span className="ml-2 text-xs text-primary">You</span>}</button></TableCell><TableCell><div className="flex items-center gap-3"><div className="hidden h-1.5 w-16 rounded-full bg-secondary sm:block"><div className={`h-full rounded-full ${b.own ? "bg-primary" : "bg-slate-400"}`} style={{ width: `${b.rate || 0}%` }}/></div><span className="tabular-nums">{rate(b.rate)}</span></div></TableCell><TableCell className="text-right tabular-nums">{b.mentions}/{b.denominator}</TableCell></TableRow>)}</TableBody></Table><p className="mt-4 text-xs leading-5 text-muted-foreground">All brands use the same selected observations. Presence measures name matches, not recommendation quality.</p></section></div>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-white p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold">Sources in the record</h2><Button variant="ghost" size="sm" onClick={() => onNavigate("sources")}>Explore sources<ArrowRight size={14}/></Button></div>{metrics.domains.length ? metrics.domains.slice(0, 5).map(d => <button key={d.domain} className="flex w-full items-center justify-between gap-4 border-b py-3 text-left last:border-0 hover:text-primary" onClick={() => show(d.domain, d.runIds, `${d.citedIds.length} answers with provider-attributed citations; ${d.manualIds.length} with manually recorded links. Other appearances may be disclosed search results.`)}><span className="truncate text-sm">{d.domain}</span><span className="shrink-0 text-xs text-muted-foreground">{d.runIds.length} answers · {d.urls.length} URLs</span></button>) : <p className="text-sm leading-6 text-muted-foreground">Disclosed sources and recorded links will appear after collection.</p>}</section><section className="rounded-xl border bg-white p-6"><h2 className="mb-4 text-base font-semibold">Evidence health</h2><div className="space-y-4 text-sm"><div className="flex justify-between"><span>Completed observations</span><strong>{metrics.eligible.length}</strong></div><div className="flex justify-between"><span>Distinct questions</span><strong>{metrics.promptCount}</strong></div><button className="flex w-full justify-between text-left hover:text-primary" onClick={() => show("Excluded observations", metrics.excluded.map(r => r.id), "Failed, partial, or empty responses do not count as brand omissions or enter presence denominators.")}><span>Incomplete or excluded</span><strong>{metrics.excluded.length}<ArrowRight className="ml-2 inline" size={14}/></strong></button><div className="flex justify-between"><span>Search activity disclosed / recorded</span><strong>{metrics.searchDisclosed}</strong></div></div><p className="mt-5 text-xs leading-5 text-muted-foreground">{metrics.methods.length > 1 ? "Multiple collection methods are selected. Separate them before drawing platform-level conclusions." : "Metrics describe this selected sample. They are not an estimate of all consumer searches."}</p></section></div>
    {inspect && <Dialog open onOpenChange={v => { if (!v) setInspect(null); }}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{inspect.title}</DialogTitle><DialogDescription>{inspect.explanation}</DialogDescription></DialogHeader><p className="text-sm text-muted-foreground">{inspect.ids.length} observations in this set</p><div className="space-y-3">{inspect.ids.slice(0,shown).map(id => { const run = metricRuns.find(r => r.id === id)!; return <button key={id} onClick={() => { setInspect(null); onOpen(id); }} className="block w-full rounded-lg border p-4 text-left hover:bg-secondary/40"><div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground">{providerNames[run.provider]} · {environments[run.environment]}<Status value={run.status}/></div><p className="text-sm font-medium">{run.prompt}</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{answerOf(run) || run.error || "No answer recorded"}</p></button>; })}{inspect.ids.length>shown&&<Button variant="outline" onClick={()=>setShown(n=>n+50)}>Show 50 more records</Button>}{!inspect.ids.length && <p className="py-6 text-sm text-muted-foreground">No observations qualify under the selected scope.</p>}</div></DialogContent></Dialog>}
  </div>;
}
