'use client';
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Textarea } from '@/components/ui/textarea';
import { api } from '@/lib/client';
import type { SelectedClaim } from '@/lib/claims';
import type { ResearchRecord,Run } from '@/lib/research';
import { Choice,Field,Note } from './ui';
import { ErrorMessage,useSavedDraft } from './workflow-ui';
export type SourceReference={sourceId:string;start:number;end:number;text:string};
export function PassageReview({run,claim,records,review,enabled,pending,onAttached,onSaved}:{run:Run;claim:SelectedClaim;records:ResearchRecord[];review?:ResearchRecord;enabled:boolean;pending:SourceReference|null;onAttached:()=>void;onSaved:()=>Promise<void>}){
 const draft=useSavedDraft(run.study_id,`passage:${run.id}:${claim.segmentIndex}:${claim.start}:${claim.end}:${review?.updated_at||'new'}`,{runId:run.id,claim:claim.text,anchor:{segmentIndex:claim.segmentIndex,start:claim.start,end:claim.end},verdict:'uncertain',evidenceLevel:'observed',materiality:'medium',factIds:[] as string[],sourceRefs:[] as SourceReference[],explanation:'',impact:'',recommendation:'',hypothesis:'',nextTest:'',...review?.payload},enabled);
 const {value:v,setValue:set}=draft;const [busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(pending){set((old:Record<string,any>)=>({...old,sourceRefs:[...(old.sourceRefs||[]).filter((x:SourceReference)=>!(x.sourceId===pending.sourceId&&x.start===pending.start&&x.end===pending.end)),pending]}));onAttached();}},[pending]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('record',{studyId:run.study_id,kind:'review',id:review?.id,expectedUpdatedAt:review?.updated_at,payload:v});await draft.clear();await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form onSubmit={save} className="space-y-4"><h3 className="text-base font-semibold">Your assessment</h3><p className="text-sm text-muted-foreground">Saved against this exact answer passage.</p><Field label="Assessment"><Choice value={v.verdict} onChange={verdict=>set({...v,verdict})} disabled={!enabled} options={[["uncertain","Insufficient evidence"],["supported","Supported"],["contradicted","Contradicted"],["mixed","Mixed support"],["context_dependent","Context dependent"]]}/></Field><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><Field label="Evidence level"><Choice value={v.evidenceLevel} onChange={evidenceLevel=>set({...v,evidenceLevel})} disabled={!enabled} options={[["observed","Observed"],["inferred","Inferred"],["experimentally_supported","Experimentally supported"],["unknown","Unknown"]]}/></Field><Field label="Priority / materiality"><Choice value={v.materiality} onChange={materiality=>set({...v,materiality})} disabled={!enabled} options={[["high","High"],["medium","Medium"],["low","Low"]]}/></Field></div>
 <fieldset className="space-y-2"><legend className="mb-2 text-sm font-medium">Dated reference facts</legend>{records.filter(r=>r.kind==='fact').map(f=><label key={f.id} className="flex items-start gap-2 rounded border p-2 text-sm"><Checkbox disabled={!enabled} checked={v.factIds.includes(f.id)} onCheckedChange={yes=>set({...v,factIds:yes?[...v.factIds,f.id]:v.factIds.filter((id:string)=>id!==f.id)})}/><span>{f.payload.claim}<span className="mt-1 block text-xs text-muted-foreground">Checked {f.payload.checkedAt}</span></span></label>)}</fieldset>
 <div className="space-y-3"><h4 className="text-sm font-medium">Attached source excerpts</h4>{v.sourceRefs?.length?v.sourceRefs.map((ref:SourceReference,i:number)=><div key={`${ref.sourceId}:${ref.start}`} className="rounded-lg border bg-blue-50/30 p-3"><blockquote className="evidence-text text-sm">{ref.text}</blockquote><p className="mt-2 text-xs text-muted-foreground">Preserved source · positions {ref.start}–{ref.end}</p><Button type="button" size="sm" variant="ghost" disabled={!enabled} onClick={()=>set({...v,sourceRefs:v.sourceRefs.filter((_:SourceReference,n:number)=>n!==i)})}>Remove excerpt</Button></div>):<p className="text-sm text-muted-foreground">Select text in a preserved source, then attach it here.</p>}</div>
 <Field label="Evidence and reasoning"><Textarea required maxLength={10000} rows={5} disabled={!enabled} value={v.explanation} onChange={e=>set({...v,explanation:e.target.value})}/></Field><Field label="Why it matters"><Textarea maxLength={4000} disabled={!enabled} rows={2} value={v.impact} onChange={e=>set({...v,impact:e.target.value})}/></Field><Field label="Recommended action"><Textarea maxLength={8000} disabled={!enabled} rows={3} value={v.recommendation} onChange={e=>set({...v,recommendation:e.target.value})}/></Field><Field label="Verification / next test"><Textarea maxLength={8000} disabled={!enabled} rows={2} value={v.nextTest} onChange={e=>set({...v,nextTest:e.target.value})}/></Field><details><summary className="text-sm cursor-pointer">Hypothesis, if any</summary><Textarea aria-label="Researcher hypothesis" value={v.hypothesis} onChange={e=>set({...v,hypothesis:e.target.value})} disabled={!enabled} maxLength={8000}/></details><Note>Attribution, factual support and causal influence are different. A later source capture cannot reveal private model reasoning.</Note><ErrorMessage message={error}/><p role="status" className="text-xs text-muted-foreground">{enabled?draft.status:'Read-only evidence view'}</p>{draft.conflict&&<Button type="button" variant="outline" onClick={draft.reload}>Reload saved draft</Button>}<Button disabled={!enabled||busy||draft.conflict||claim.text.length>6000}>{busy?'Saving…':review?'Save revised assessment':'Save assessment'}</Button></form>;
}
