"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Plus,Package } from "lucide-react";
import { intelligenceApi } from "@/lib/client";
import type { ResearchRecord,Study } from "@/lib/research";
import { Choice,Field,SourceLink,Status } from "./ui";
import { Card,EmptyState,ErrorMessage,BusyButton,useSavedDraft } from "./workflow-ui";
export function Products({study,records,enabled,onRefresh}:{study:Study;records:ResearchRecord[];enabled:boolean;onRefresh:()=>Promise<void>}){
  const [editing,setEditing]=useState<ResearchRecord|"new"|null>(null),products=records.filter(r=>r.kind==="product");
  return <div className="space-y-6"><Card title="Keep the product identity precise" description="Separate product families, SKUs, regional variants, and retailer offers. Dates make an old specification distinguishable from a current contradiction." action={<Button disabled={!enabled} onClick={()=>setEditing("new")}><Plus size={15}/>Add product or offer</Button>}><div className="grid gap-4 sm:grid-cols-3">{[["Identity","A product name, SKU, and variant."],["Context","The market, retailer, and authoritative page."],["Time","The period in which this reference applies."]].map(([h,t])=><div className="rounded-lg bg-secondary/50 p-4" key={h}><h3 className="text-sm font-semibold">{h}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{t}</p></div>)}</div></Card>{products.length?<div className="grid gap-5 lg:grid-cols-2">{products.map(p=><Card key={p.id} title={p.payload.name} action={<Status value={p.payload.status}/>}><dl className="grid grid-cols-2 gap-4 text-sm">{[["SKU",p.payload.sku],["Variant",p.payload.variant],["Market",p.payload.market],["Retailer",p.payload.retailer],["Valid from",p.payload.validFrom],["Valid through",p.payload.validThrough]].map(([label,value])=><div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1">{value||"Not specified"}</dd></div>)}</dl>{p.payload.description&&<p className="mt-5 text-sm leading-7">{p.payload.description}</p>}{p.payload.url&&<p className="mt-4 text-sm"><SourceLink url={p.payload.url}/></p>}<div className="mt-5 border-t pt-4"><Button variant="outline" size="sm" disabled={!enabled} onClick={()=>setEditing(p)}>Update reference</Button></div></Card>)}</div>:<EmptyState title="Give each offer its own reference"><Package className="mx-auto mb-3 text-primary"/>A brand can be represented correctly overall while an agent recommends an obsolete version. Track the distinctions here.</EmptyState>}{editing&&<ProductForm key={editing==="new"?"new":editing.id} study={study} record={editing==="new"?undefined:editing} onClose={()=>setEditing(null)} onRefresh={onRefresh}/>}</div>;
}
function ProductForm({study,record,onClose,onRefresh}:{study:Study;record?:ResearchRecord;onClose:()=>void;onRefresh:()=>Promise<void>}){
  const {value:v,setValue:setV,status,reload,conflict,clear}=useSavedDraft(study.id,`product:${record?.id||"new"}:${record?.updated_at||0}`,{name:"",sku:"",variant:"",market:study.profile?.market||"",retailer:"",url:"",validFrom:"",validThrough:"",description:"",status:"current",...record?.payload});
  const [busy,setBusy]=useState(false),[error,setError]=useState("");const set=(k:string,s:string)=>setV((old:any)=>({...old,[k]:s}));
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await intelligenceApi("product",{studyId:study.id,id:record?.id,expectedUpdatedAt:record?.updated_at,...v});await clear().catch(()=>{});await onRefresh();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{record?"Update product reference":"Add product or offer"}</DialogTitle><DialogDescription>Reference changes retain previous versions. They do not rewrite earlier claim assessments.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-5"><Field label="Product or offer name"><Input required value={v.name} onChange={e=>set("name",e.target.value)}/></Field><div className="grid gap-4 sm:grid-cols-2">{[["sku","SKU"],["variant","Variant / edition"],["market","Market"],["retailer","Retailer"]].map(([key,label])=><Field key={key} label={label}><Input value={v[key]} onChange={e=>set(key,e.target.value)}/></Field>)}<Field label="Valid from"><Input type="date" value={v.validFrom} onChange={e=>set("validFrom",e.target.value)}/></Field><Field label="Valid through"><Input type="date" value={v.validThrough} onChange={e=>set("validThrough",e.target.value)}/></Field></div><Field label="Reference URL"><Input type="url" value={v.url} onChange={e=>set("url",e.target.value)}/></Field><Field label="Description / distinction"><Textarea rows={4} value={v.description} onChange={e=>set("description",e.target.value)}/></Field><Field label="Reference status"><Choice value={v.status} onChange={s=>set("status",s)} options={[["current","Current"],["superseded","Superseded"],["uncertain","Uncertain"]]}/></Field><p role="status" className="text-xs text-muted-foreground">{status}</p>{conflict&&<Button type="button" variant="outline" onClick={reload}>Reload saved draft</Button>}<ErrorMessage message={error}/><BusyButton busy={busy}>Save product reference</BusyButton></form></DialogContent></Dialog>;
}
