"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Field, Choice } from "./ui";
export function ReportReader({ token, title, createdAt, expiresAt, html, findings }: { token: string; title: string; createdAt: string; expiresAt: string; html: string; findings: { id: string; claim: string }[] }) {
  const [author, setAuthor] = useState(""), [message, setMessage] = useState(""), [reviewId, setReviewId] = useState("general"), [busy, setBusy] = useState(false), [status, setStatus] = useState("");
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setStatus("");
    try { const response = await fetch("/api/report-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, author, message, reviewId: reviewId === "general" ? null : reviewId }) }); const data: any = await response.json(); if (!response.ok) throw new Error(data.error); setMessage(""); setStatus("Your comment has been saved for the researcher."); } catch (e) { setStatus((e as Error).message); } finally { setBusy(false); }
  }
  return <main className="mx-auto max-w-[1500px] p-5 sm:p-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-primary">Brand Research / Client review</p><h1 className="mt-2 text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">Saved {new Date(createdAt).toLocaleDateString()} · Link expires {new Date(expiresAt).toLocaleDateString()}</p></div><Button variant="outline" onClick={() => { const url = URL.createObjectURL(new Blob([html], { type: "text/html" })); const a = document.createElement("a"); a.href = url; a.download = "brand-research-report.html"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}>Download report</Button></header><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><iframe title="Saved client report" srcDoc={html} referrerPolicy="no-referrer" sandbox="allow-popups allow-popups-to-escape-sandbox" className="h-[85vh] min-h-[650px] w-full rounded-xl border bg-white"/><aside className="rounded-xl border bg-white p-6 xl:sticky xl:top-6"><h2 className="text-lg font-semibold">Question a finding</h2><p className="mb-5 mt-2 text-sm leading-6 text-muted-foreground">Add context, a correction, or a source for the researcher to review. The saved evidence stays unchanged.</p><form onSubmit={submit} className="space-y-4"><Field label="Your name"><Input required maxLength={120} value={author} onChange={e => setAuthor(e.target.value)}/></Field><Field label="About"><Choice value={reviewId} onChange={setReviewId} options={[["general", "The overall report"], ...findings.map(f => [f.id, f.claim.slice(0, 90)] as [string, string])]}/></Field><Field label="Comment or supporting source"><Textarea required minLength={5} maxLength={5000} rows={6} value={message} onChange={e => setMessage(e.target.value)}/></Field><Button disabled={busy} className="w-full">{busy ? "Saving…" : "Send for review"}</Button>{status && <p role="status" className="text-sm leading-6">{status}</p>}<p className="text-xs leading-5 text-muted-foreground">Anyone with this active link and access to the site can read this report and submit a named comment. Names are supplied by reviewers and are not independently verified.</p></form></aside></div></main>;
}
