"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Download,FileUp } from "lucide-react";
import { displayDate,intelligenceApi } from "@/lib/client";
import { parseCsv } from "@/lib/imports";
import type { ResearchRecord,Study } from "@/lib/research";
import { Choice,Field,Note } from "./ui";
import { Card,EmptyState,ErrorMessage,BusyButton } from "./workflow-ui";
const labels:Record<string,string>={ga4:"GA4 referral sessions",search_console:"Search Console query clicks",crawler_log:"Crawler requests"};
export function Traffic({study,records,enabled,onRefresh}:{study:Study;records:ResearchRecord[];enabled:boolean;onRefresh:()=>Promise<void>}){
  const imports=records.filter(r=>r.kind==="traffic"),[kind,setKind]=useState("ga4"),[csv,setCsv]=useState(""),[name,setName]=useState(""),[headers,setHeaders]=useState<string[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[notes,setNotes]=useState(""),[preview,setPreview]=useState<any>(null),[partial,setPartial]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function file(e:React.ChangeEvent<HTMLInputElement>){setError("");setPreview(null);const file=e.target.files?.[0];if(!file)return;if(file.size>1500000){setError("Choose a CSV smaller than 1.5 MB.");return;}try{const text=await file.text(),rows=parseCsv(text.replace(/^\uFEFF/,""));if(rows.length<2)throw new Error("The file needs a header and at least one row.");setCsv(text);setName(file.name);const h=rows[0].map(s=>s.trim());setHeaders(h);const aliases:Record<string,string[]>={date:["date","day"],source:["source","session source","session source / medium","referrer","host"],query:["query","top queries"],page:["page","landing page","url"],count:["sessions","clicks","requests","count"],impressions:["impressions"],country:["country"],userAgent:["user agent","user-agent","useragent"]};const m:Record<string,string>={};for(const [key,names]of Object.entries(aliases)){const match=h.find(x=>names.includes(x.toLowerCase()));if(match)m[key]=match;}setMapping(m);}catch(e){setError((e as Error).message);}}
  async function perform(save=false){setBusy(true);setError("");try{const data=await intelligenceApi(save?"traffic_import":"traffic_preview",{studyId:study.id,kind,csv,name,notes,mapping,acceptRejected:partial});if(save){await onRefresh();setCsv("");setHeaders([]);setPreview(null);}else setPreview(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="space-y-6"><Card title="Bring observed traffic into the investigation" description="Import an export you control. Dates, row validation, source labels, and the original file stay with each dataset."><div className="grid gap-5 md:grid-cols-2"><Field label="Dataset type"><Choice value={kind} onChange={s=>{setKind(s);setPreview(null);}} options={Object.entries(labels)} disabled={!enabled||busy}/></Field><Field label="CSV export" hint="Up to 20,000 rows, 1.5 MB. Include a date column; aggregated exports without dates need a dated export first."><Input type="file" accept=".csv,text/csv" disabled={!enabled||busy} onChange={file}/></Field></div>{headers.length>0&&<div className="mt-6 space-y-5"><Field label="Dataset name"><Input value={name} onChange={e=>setName(e.target.value)}/></Field><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["date","Date · required"],["count",kind==="ga4"?"Sessions · required":kind==="search_console"?"Clicks · required":"Requests · required"],[kind==="search_console"?"query":"source",kind==="search_console"?"Query · required":"Source / referrer · required"],["page","Page · optional"],["impressions","Impressions · optional"],["country","Country · optional"],...(kind==="crawler_log"?[["userAgent","User-agent · optional"]]:[])].map(([key,label])=><Field key={key} label={label}><Choice value={mapping[key]||"none"} onChange={v=>{setMapping(old=>({...old,[key]:v==="none"?"":v}));setPreview(null);}} options={[["none","Choose a column"],...headers.map(h=>[h,h] as [string,string])]}/></Field>)}</div><Field label="Coverage and collection notes"><Textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Property, filters, time zone, bot verification method, or missing coverage…"/></Field><BusyButton variant="outline" busy={busy} disabled={!enabled} onClick={()=>perform()}><FileUp size={15}/>Validate and preview</BusyButton></div>}<div className="mt-4"><ErrorMessage message={error}/></div>
      {preview&&<div className="mt-6 border-t pt-5"><h3 className="font-semibold">{preview.summary.rows} valid rows · {preview.summary.rejected} rejected</h3><p className="mt-2 text-sm text-muted-foreground">{preview.summary.from} through {preview.summary.to} · {preview.summary.total.toLocaleString()} {kind==="ga4"?"sessions":kind==="search_console"?"clicks":"requests"}</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Date</th><th className="p-2">Source / query</th><th className="p-2">Count</th><th className="p-2">Page</th></tr></thead><tbody>{preview.sample.map((r:any,i:number)=><tr key={i} className="border-b"><td className="p-2">{r.date}</td><td className="p-2">{kind==="search_console"?r.query:r.source}</td><td className="p-2">{r.count}</td><td className="max-w-sm break-all p-2">{r.page||"—"}</td></tr>)}</tbody></table></div>{preview.errors.length>0&&<div className="mt-4 rounded-lg bg-amber-50 p-4 text-sm"><p className="font-medium">Rejected rows</p><ul className="my-3 list-disc space-y-1 pl-5">{preview.errors.slice(0,10).map((e:any)=><li key={e.row}>Row {e.row}: {e.reason}</li>)}</ul><label className="flex items-start gap-2"><input type="checkbox" checked={partial} onChange={e=>setPartial(e.target.checked)}/>Save only valid rows and retain the rejection log.</label></div>}<BusyButton className="mt-5" busy={busy} disabled={!preview.summary.rows||preview.summary.rejected>0&&!partial} onClick={()=>perform(true)}>Save validated dataset</BusyButton></div>}
    </Card><Note>These imports are separate datasets. Overlapping exports are not added together. Search Console query volume is not AI prompt volume; referrer sessions and crawler user agents do not prove a citation, ranking effect, or revenue impact.</Note>
    {imports.length?imports.map(r=><Card key={r.id} title={r.payload.name} description={`${labels[r.payload.kind]} · imported ${displayDate(r.created_at)}`} action={<Button asChild size="sm" variant="outline"><a href={`/api/intelligence?studyId=${study.id}&id=${r.id}`}><Download size={14}/>Source dataset</a></Button>}><div className="mb-5 flex flex-wrap gap-6"><div><p className="text-2xl font-semibold tabular-nums">{r.payload.summary.total.toLocaleString()}</p><p className="mt-1 text-sm text-muted-foreground">{r.payload.metric} in this export</p></div><div><p className="text-sm font-medium">{r.payload.summary.from} → {r.payload.summary.to}</p><p className="mt-1 text-sm text-muted-foreground">{r.payload.summary.rows} accepted rows · {r.payload.summary.rejected} rejected</p></div></div><div className="space-y-3">{r.payload.summary.top.slice(0,10).map((s:any)=><div key={s.label} className="flex justify-between gap-4 border-t pt-3 text-sm"><span className="break-all">{s.label}</span><span className="font-medium tabular-nums">{s.count.toLocaleString()}</span></div>)}</div><p className="mt-5 text-sm leading-6 text-muted-foreground">{r.payload.limitations}</p>{r.payload.notes&&<p className="mt-3 text-sm leading-6"><strong>Coverage: </strong>{r.payload.notes}</p>}</Card>):<EmptyState title="No first-party datasets yet">Import referral, query, or crawler evidence to put AI observations in context.</EmptyState>}
  </div>;
}
