"use client";
import { lazy, Suspense, useEffect, useRef, useState, type CSSProperties } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Toaster } from "@/components/ui/sonner";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ArrowLeft, ArrowLeftRight, ArrowRight, BookOpen, ChartNoAxesCombined, ChevronRight, Download, FileCheck2, FlaskConical, FolderOpen, KeyRound, Layers3, Link2, Loader2, LockKeyhole, MessageSquareText, Plus, RefreshCw, ScanText, SlidersHorizontal, Target } from "lucide-react";
import { toast } from "sonner";
import { readApi, download, displayDate } from "@/lib/client";
import { environments, providerNames, type ResearchRecord, type Run, type Study } from "@/lib/research";
import { emptyScope, scopeRuns, type Scope } from "@/lib/analytics";
import { exampleRecords, exampleRuns, exampleStudy } from "@/lib/example";
import { StudyForm, RecordForm } from "./forms";
import { Onboarding } from "./onboarding";
import { CollectForm, emptyConnections } from "./collect";
import { CollectionPlan } from "./collection-plan";
import { ConnectionsPage } from "./connections";
const ComparePage = lazy(() => import("./compare").then(module => ({ default: module.ComparePage })));
import { Inspector } from "./inspector";
const Overview = lazy(() => import("./overview").then(module => ({ default: module.Overview })));
import { Narrative } from "./narrative";
import { Sources } from "./sources";
import { Decisions } from "./decisions";
const Delivery = lazy(() => import("./delivery").then(module => ({ default: module.Delivery })));
import { MethodPage } from "./method";
import { QuestionTools } from "./question-tools";
import type { SelectedClaim } from "@/lib/claims";
import { Choice, Note, SourceLink, Status } from "./ui";

type Section = "overview" | "observations" | "questions" | "collect" | "narrative" | "sources" | "compare" | "decisions" | "report" | "facts" | "connections" | "method";
const sections = [
  { id: "overview", label: "Brand portrait", icon: ChartNoAxesCombined },
  { id: "observations", label: "Observations", icon: ScanText },
  { id: "narrative", label: "Narrative analysis", icon: Layers3 },
  { id: "sources", label: "Source library", icon: Link2 },
  { id: "compare", label: "Compare answers", icon: ArrowLeftRight },
  { id: "decisions", label: "Decisions & actions", icon: Target },
  { id: "report", label: "Client reports", icon: FileCheck2 },
] as const;
const setup = [{ id: "questions", label: "Customer questions", icon: MessageSquareText }, { id: "collect", label: "Collect evidence", icon: FlaskConical }, { id: "facts", label: "Brand facts", icon: FileCheck2 }, { id: "connections", label: "Connections", icon: KeyRound }, { id: "method", label: "Research guide", icon: BookOpen }] as const;
const allSections = [...sections, ...setup];
const scopedSections: Section[] = ["overview", "observations", "narrative", "sources", "compare", "decisions", "report"];
const titles: Record<Section, [string, string]> = {
  overview: ["Your brand, through AI", "Understand the picture forming around your brand. Follow every measurement back to the answers behind it."],
  observations: ["The evidence, in full", "Open an answer. Select a passage. Inspect the sources and the conditions that produced the record."],
  narrative: ["What the answers are saying", "Evidence-linked themes, buyer fit, and possible factual conflicts — ready for your assessment."],
  sources: ["Where the answers point", "Inspect disclosed URLs, preserve source excerpts, and see which answers connect to each page."],
  decisions: ["Make the research useful", "Review what matters, agree on an action, and retain the evidence used to test its outcome."],
  report: ["A clear story. A visible trail.", "Review and share a dated investigation that clients can inspect and question."],
  facts: ["A reference you can defend", "Keep dated product facts and contradictory evidence separate from your desired positioning."],
  questions: ["Start where customers start", "A reusable research set covering discovery, comparison, purchase, verification, and support."],
  collect: ["Build a repeatable study", "Plan across providers and repeat questions. Record consumer-app observations alongside API experiments."],
  compare: ["See what changed", "Compare answer wording, source disclosure, and experimental conditions side by side."],
  connections: ["Connect your research accounts", "Use your provider API accounts. Credentials stay in this tab’s memory and are never saved with evidence."],
  method: ["Know what the evidence means", "A practical guide to observable behavior, uncertainty, and responsible interpretation."],
};
function WorkspaceSidebar({ section, onNavigate, user, demo }: { section: Section; onNavigate: (s: Section) => void; user: { displayName: string } | null; demo: boolean }) {
  const { setOpenMobile } = useSidebar();
  const group = (items: Readonly<typeof allSections>, label: string) => <SidebarGroup className="px-3"><SidebarGroupLabel className="mb-2 px-3 text-[11px] tracking-[0.14em]">{label}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu className="gap-1">{items.map(item => <SidebarMenuItem key={item.id}><SidebarMenuButton className="h-10 px-3 text-sm" isActive={section === item.id} onClick={() => { onNavigate(item.id); setOpenMobile(false); }}><item.icon size={17}/><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup>;
  return <Sidebar className="border-r" collapsible="offcanvas"><SidebarHeader className="px-6 pb-6 pt-7"><div className="flex items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary font-serif text-2xl text-white">R<span className="ml-0.5 text-sm">/</span></span><div><p className="text-sm font-semibold text-sidebar-foreground">Brand Research</p><p className="mt-1 text-xs text-sidebar-foreground/60">Evidence → understanding</p></div></div></SidebarHeader><SidebarContent>{group(sections, "INTELLIGENCE")}{group(setup, "RESEARCH SETUP")}</SidebarContent><SidebarFooter className="gap-4 border-t border-sidebar-border p-5"><div className="flex items-start gap-2 text-xs leading-5 text-sidebar-foreground/65"><LockKeyhole size={13} className="mt-1 shrink-0"/><span>{demo ? "Fictional example. No provider was queried." : "Your account’s workspace. Share only the reports you choose."}</span></div><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-white/10 text-sm">{user?.displayName?.slice(0, 1).toUpperCase() || "R"}</span><p className="truncate text-sm">{user?.displayName || "Researcher"}</p></div></SidebarFooter></Sidebar>;
}
export function Workbench({ user }: { user: { displayName: string } | null }) {
  const [section, setSection] = useState<Section>("overview"), [scope, setScope] = useState<Scope>(emptyScope);
  const [studies, setStudies] = useState<Study[]>([]), [studyId, setStudyId] = useState("");
  const [runs, setRuns] = useState<Run[]>([]), [records, setRecords] = useState<ResearchRecord[]>([]), [totalRuns, setTotalRuns] = useState(0);
  const [selectedId, setSelectedId] = useState(""), [detail, setDetail] = useState<Run | null>(null);
  const [loading, setLoading] = useState(!!user), [error, setError] = useState(""), [demo, setDemo] = useState(false), [ready, setReady] = useState(false);
  const [onboarding, setOnboarding] = useState<"new" | "edit" | null>(null), [editStudy, setEditStudy] = useState(false);
  const [recordForm, setRecordForm] = useState<{ kind: "fact" | "question" | "review"; record?: ResearchRecord; selection?: SelectedClaim } | null>(null);
  const [collect, setCollect] = useState<{ prompt: string; mode?: string } | null>(null), [connections, setConnections] = useState(emptyConnections);
  const loadSequence = useRef(0), currentStudy = useRef("");
  const study = studies.find(s => s.id === studyId), selected = detail?.id === selectedId ? detail : runs.find(r => r.id === selectedId);
  const facts = records.filter(r => r.kind === "fact"), questions = records.filter(r => r.kind === "question"), enabled = !!user && !demo;
  const visibleRuns = scopeRuns(runs, records, scope);
  async function refresh(id = studyId, selectId?: string, force = false) {
    if (!user || (demo && !force)) return; const seq = ++loadSequence.current; setLoading(true); setError("");
    try { const data = await readApi("state", id ? { studyId: id } : {}); if (seq !== loadSequence.current) return;
      const changed = currentStudy.current !== data.studyId; currentStudy.current = data.studyId || "";
      setStudies(data.studies); setStudyId(data.studyId || ""); setRuns(data.runs); setRecords(data.records); setTotalRuns(data.totalRuns ?? data.runs.length);
      if (changed) setDetail(null);
      setSelectedId(current => selectId || (data.runs.some((r: Run) => r.id === current) ? current : data.runs[0]?.id || ""));
      if (changed && !new URLSearchParams(window.location.search).has("environment")) setScope(prev => ({ ...prev, environment: data.runs.find((r: Run) => r.environment === "consumer") ? "consumer" : data.runs[0]?.environment || "consumer" }));
      if (selectId) { const r = data.runs.find((r: Run) => r.id === selectId); if (r) setScope({ ...emptyScope(), environment: r.environment }); }
    } catch (e) { if (seq === loadSequence.current) setError((e as Error).message); } finally { if (seq === loadSequence.current) setLoading(false); }
  }
  function explore() { loadSequence.current++; setLoading(false); setError(""); setDemo(true); setStudies([exampleStudy]); setStudyId(exampleStudy.id); setRuns(exampleRuns); setTotalRuns(exampleRuns.length); setRecords(exampleRecords); setSelectedId(exampleRuns[0].id); setDetail(null); setScope({ ...emptyScope(), environment: "api" }); setSection("overview"); }
  function exitDemo() { setStudies([]); setStudyId(""); currentStudy.current = ""; setRuns([]); setRecords([]); setSelectedId(""); setDetail(null); setScope(emptyScope()); setDemo(false); setSection("overview"); window.history.replaceState(null, "", "/"); void refresh("", undefined, true); }
  useEffect(() => { const p = new URLSearchParams(window.location.search); const s = p.get("section"); if (allSections.some(x => x.id === s)) setSection(s as Section); setScope({ ...emptyScope(), ...Object.fromEntries(Object.keys(emptyScope()).filter(k => p.has(k)).map(k => [k, p.get(k)!])) }); if (p.get("example") === "1") explore(); else if (user) void refresh(p.get("study") || "", p.get("run") || undefined); setReady(true); }, [user]);
  useEffect(() => { if (!ready || loading) return; const p = new URLSearchParams(); if (studyId) p.set("study", studyId); p.set("section", section); if (demo) p.set("example", "1"); for (const [key, value] of Object.entries(scope)) if (value) p.set(key, value); if (selectedId && section === "observations") p.set("run", selectedId); window.history.replaceState(null, "", `/?${p}`); }, [ready, loading, studyId, section, scope, selectedId, demo]);
  useEffect(() => { const onPop = () => { const p = new URLSearchParams(window.location.search); const s = p.get("section"); if (allSections.some(x => x.id === s)) setSection(s as Section); setScope({ ...emptyScope(), ...Object.fromEntries(Object.keys(emptyScope()).filter(k => p.has(k)).map(k => [k, p.get(k)!])) }); setSelectedId(p.get("run") || ""); if (p.get("study") && p.get("study") !== studyId && enabled) void refresh(p.get("study")!); }; window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, [studyId, enabled]);
  useEffect(() => { let current = true; if (selectedId && !demo && user) readApi("run", { id: selectedId }).then(data => { if (current && data.run.study_id === studyId) setDetail(data.run); }).catch(e => { if (current) toast.error(e.message); }); return () => { current = false; }; }, [selectedId, studyId, demo, user]);
  function navigate(s: string) { if (!allSections.some(x => x.id === s)) return; if (s !== section) window.history.pushState(null, "", window.location.href); setSection(s as Section); }
  function openRun(id: string) { setSelectedId(id); navigate("observations"); }
  async function refreshRun() { await refresh(); if (selectedId) { const data = await readApi("run", { id: selectedId }); setDetail(data.run); } }
  async function exportStudy() { try { download(await readApi("export", { studyId }), `study-${studyId}.json`); toast.success("Study export downloaded."); } catch (e) { toast.error((e as Error).message); } }
  useEffect(() => {
    const ctx = (document as any).modelContext; if (!ctx?.registerTool) return; const lifecycle = new AbortController();
    const register = (tool: any) => { try { Promise.resolve(ctx.registerTool(tool, { signal: lifecycle.signal })).catch(() => {}); } catch {} };
    register({ name: "read_current_research", title: "Read current research", description: "Read visible research scope and observations. No API keys or provider requests.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute(input: any) { if (!input || Object.keys(input).length) throw new Error("Expected an empty object."); return { study, example: demo, section, scope, responses: visibleRuns.map(r => ({ id: r.id, prompt: r.prompt, provider: r.provider, environment: r.environment, status: r.status })), selectedResponse: selected ? { id: selected.id, normalized: selected.normalized } : null }; } });
    register({ name: "select_research_response", title: "Select a response", description: "Open an existing observation without making provider requests.", inputSchema: { type: "object", properties: { responseId: { type: "string" } }, required: ["responseId"], additionalProperties: false }, annotations: { readOnlyHint: false }, execute(input: any) { if (!input || Object.keys(input).some(k => k !== "responseId") || !runs.some(r => r.id === input.responseId)) throw new Error("Choose a response in this study."); openRun(input.responseId); return { selectedResponseId: input.responseId }; } }); return () => lifecycle.abort();
  }, [study, runs, selected, section, demo, scope]);
  return <SidebarProvider style={{ "--sidebar-width": "244px" } as CSSProperties}><WorkspaceSidebar section={section} onNavigate={navigate} user={user} demo={demo}/><SidebarInset className="min-w-0 bg-background"><header className="flex h-[76px] shrink-0 items-center justify-between gap-3 border-b bg-white px-4 sm:px-8"><div className="flex min-w-0 items-center gap-3"><SidebarTrigger className="md:hidden"/><span className="hidden text-sm text-muted-foreground sm:block">Workspace</span><ChevronRight size={14} className="hidden text-slate-300 sm:block"/><div className="w-[min(40vw,260px)]">{studies.length ? <Choice label="Selected brand study" value={studyId} onChange={id => { setScope(emptyScope()); setSelectedId(""); setDetail(null); void refresh(id); }} options={studies.map(s => [s.id, s.name])} disabled={demo || loading}/> : <span className="text-sm font-medium">Brand research</span>}</div></div><Button variant="outline" size="sm" disabled={!enabled} onClick={() => setOnboarding("new")}><Plus size={15}/>New brand</Button></header>
    <div className="mx-auto w-full max-w-[1680px] p-4 sm:p-8 lg:px-10">
      {demo && <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><span><strong>Example workspace.</strong> Fictional brand, answers, and findings. No real searches.</span><Button variant="ghost" size="sm" className="text-amber-900" onClick={exitDemo}><ArrowLeft size={14}/>My workspace</Button></div>}
      {!user && !demo && <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm"><span>Sign in to create a brand workspace and save your research.</span><Button asChild size="sm"><a target="_top" href="/signin-with-chatgpt?return_to=%2F">Sign in with ChatGPT<ArrowRight size={14}/></a></Button></div>}
      <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.17em] text-primary">{study?.brand || "Brand Research"} / {allSections.find(x => x.id === section)?.label}</p><h1 className="text-3xl font-semibold tracking-[-0.035em] sm:text-[34px] sm:leading-[1.2]">{titles[section][0]}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{titles[section][1]}</p></div><div className="flex gap-2">{section === "observations" && study && <><Button size="sm" variant="outline" disabled={!enabled} onClick={exportStudy}><Download size={15}/>Export</Button><Button size="sm" disabled={!enabled} onClick={() => setCollect({ prompt: "" })}><Plus size={15}/>Add observation</Button></>}{["facts", "questions"].includes(section) && <Button size="sm" disabled={!study || !enabled} onClick={() => setRecordForm({ kind: section === "facts" ? "fact" : "question" })}><Plus size={15}/>Add {section === "facts" ? "fact" : "question"}</Button>}</div></div>
      {error && <div className="mb-5 flex items-center justify-between gap-3 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p role="alert">{error}</p><Button variant="outline" size="sm" onClick={() => refresh()}>Try again</Button></div>}
      {loading && <p role="status" className="mb-4 flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="animate-spin" size={15}/>Loading research…</p>}
      {study && scopedSections.includes(section) && <div className="mb-6 rounded-xl border bg-white p-4"><div className="mb-3 flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground"><SlidersHorizontal size={14}/>Evidence scope</span><span className="text-xs text-muted-foreground">{visibleRuns.length} of {runs.length} loaded observations</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Choice label="Collection method" value={scope.environment} onChange={environment => setScope({ ...scope, environment })} options={[["consumer", "Consumer-app observations"], ["api", "API experiments"], ["imported", "Imported API responses"], ["all", "All methods · mixed"]]}/><Choice label="Provider" value={scope.provider} onChange={provider => setScope({ ...scope, provider })} options={[["all", "All providers"], ...Array.from(new Set(runs.map(r => r.provider))).map(p => [p, providerNames[p]] as [string, string])]}/><Choice label="Question intent" value={scope.intent} onChange={intent => setScope({ ...scope, intent })} options={[["all", "All intents"], ...["discovery", "comparison", "verification", "purchase", "support"].map(s => [s, s] as [string, string])]}/><div><label className="mb-1.5 block text-xs text-muted-foreground" htmlFor="scope-from">From · observation date</label><Input id="scope-from" type="date" value={scope.from} onChange={e => setScope({ ...scope, from: e.target.value })}/></div><div><label className="mb-1.5 block text-xs text-muted-foreground" htmlFor="scope-to">Through · UTC</label><Input id="scope-to" type="date" value={scope.to} onChange={e => setScope({ ...scope, to: e.target.value })}/></div></div><div className="mt-3 flex flex-wrap items-center gap-3"><Input className="max-w-md" aria-label="Search prompts and answers" placeholder="Search prompts and answer text…" value={scope.query} onChange={e => setScope({ ...scope, query: e.target.value })}/><Button size="sm" variant="ghost" onClick={() => setScope({ ...emptyScope(), environment: scope.environment })}>Reset filters</Button>{scope.from && scope.to && scope.from > scope.to && <span role="alert" className="text-xs text-destructive">Start date is after end date.</span>}</div>{totalRuns > runs.length && <p className="mt-3 text-sm text-amber-800">This view uses the latest {runs.length} of {totalRuns} observations. Metrics and reports describe this loaded subset.</p>}</div>}
      {!study && !loading && !["connections", "method"].includes(section) && <div className="grid overflow-hidden rounded-2xl border bg-white lg:grid-cols-[1.2fr_1fr]"><div className="p-7 sm:p-10"><div className="mb-8 flex size-14 items-center justify-center rounded-xl bg-blue-50 text-primary"><ScanText size={28} strokeWidth={1.5}/></div><h2 className="max-w-md text-2xl font-semibold tracking-tight">Turn an AI answer into something you can investigate.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-muted-foreground">Set up your brand and the questions your customers ask. Collect answers, trace the evidence, and decide what deserves attention.</p><div className="mt-7 flex flex-wrap gap-3"><Button disabled={!enabled} onClick={() => setOnboarding("new")}>Set up my first brand<ArrowRight size={16}/></Button><Button variant="outline" onClick={explore}>Explore the example</Button></div></div><div className="border-t bg-slate-50 p-7 sm:p-10 lg:border-l lg:border-t-0"><p className="mb-7 text-xs font-semibold uppercase tracking-widest text-muted-foreground">Your first investigation</p>{[["01", "Define the brand", "Audience, competitors, positioning, and dated product facts."], ["02", "Collect real observations", "API experiments, original response imports, and consumer-app records."], ["03", "Understand and act", "Measured presence, evidence-linked interpretation, and a reviewable report."]].map(([n, title, text]) => <div key={n} className="mb-7 flex gap-4"><span className="pt-1 font-mono text-xs text-primary">{n}</span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></div>}
      {study && section === "overview" && <Suspense fallback={<p role="status" className="py-10 text-sm text-muted-foreground">Opening brand portrait…</p>}><Overview study={study} runs={visibleRuns} records={records} onOpen={openRun} onNavigate={navigate} onCollect={() => navigate("collect")} onProfile={() => enabled ? setOnboarding("edit") : toast.info("Brand settings are read-only in the example.")}/></Suspense>}
      {study && section === "observations" && <div className="research-grid min-h-[620px] overflow-hidden rounded-xl border bg-white"><aside className="border-b bg-[#fcfdff] lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b px-4 py-4"><h2 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Recorded answers · {visibleRuns.length}</h2><Button variant="ghost" size="icon" className="size-7" aria-label="Refresh observations" disabled={!enabled || loading} onClick={() => refresh()}><RefreshCw size={14}/></Button></div><div className="max-h-[820px] overflow-y-auto">{visibleRuns.map(run => <button key={run.id} className={`w-full border-b border-l-[3px] p-4 text-left transition-colors ${selectedId === run.id ? "border-l-primary bg-blue-50/70" : "border-l-transparent hover:bg-slate-50"}`} onClick={() => setSelectedId(run.id)}><div className="mb-2 flex justify-between gap-2"><span className="text-xs font-semibold text-slate-500">{providerNames[run.provider]}</span><span className="text-[11px] text-muted-foreground">{displayDate(run.created_at)}</span></div><p className="line-clamp-3 text-sm font-medium leading-6">{run.prompt}</p><div className="mt-3 flex items-center justify-between gap-2"><span className="text-xs text-muted-foreground">{environments[run.environment]}</span><Status value={run.status}/></div></button>)}{!visibleRuns.length && <div className="px-6 py-12 text-center"><FolderOpen size={26} className="mx-auto mb-3 text-slate-300"/><p className="text-sm font-medium">No observations in this scope</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Adjust the collection method or filters, or add your first record.</p></div>}</div></aside><div className="min-w-0">{selected && !visibleRuns.some(r => r.id === selected.id) && <div className="border-b bg-amber-50 p-4 text-sm text-amber-900">This linked observation is outside your current filters. It is open for inspection and excluded from the scoped metrics.</div>}{selected ? <Inspector run={selected} records={records} demo={demo} onReview={selection => setRecordForm({ kind: "review", selection })} onEditReview={record => setRecordForm({ kind: "review", record })} onRefresh={refreshRun} onRepeat={() => setCollect({ prompt: selected.prompt })}/> : <div className="flex min-h-[500px] flex-col items-center justify-center p-8 text-center"><ScanText size={32} className="mb-5 text-primary"/><h2 className="text-xl font-semibold">The original answer is the starting point.</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">Select an observation to inspect passages, citations, disclosed searches, and your assessments.</p><Button className="mt-6" disabled={!enabled} onClick={() => setCollect({ prompt: "" })}>Add an observation</Button></div>}</div></div>}
      {study && section === "narrative" && <Narrative study={study} runs={visibleRuns} records={records} enabled={enabled} connections={connections} onRefresh={refresh} onOpen={openRun} onConnect={() => navigate("connections")}/>}
      {study && section === "sources" && <Sources study={study} runs={visibleRuns} records={records} enabled={enabled} onOpen={openRun} onRefresh={refresh}/>}
      {study && section === "decisions" && <Decisions study={study} runs={visibleRuns} records={records} enabled={enabled} onEdit={record => setRecordForm({ kind: "review", record })} onOpen={openRun} onRefresh={refresh}/>}
      {study && section === "report" && <Suspense fallback={<p role="status">Opening report workspace…</p>}><Delivery key={study.id} study={study} runs={visibleRuns} records={records} enabled={enabled}/></Suspense>}
      {study && section === "collect" && <CollectionPlan key={study.id} study={study} records={records} connections={connections} enabled={enabled} onRefresh={refresh} onOpen={openRun} onCapture={mode => setCollect({ prompt: "", mode })} onQuestions={() => navigate("questions")} onConnect={() => navigate("connections")}/>}
      {study && section === "facts" && <div className="space-y-4"><div className="mb-5 flex flex-wrap gap-3"><Button variant="outline" disabled={!enabled} onClick={() => setOnboarding("edit")}>Positioning & competitors</Button><Button variant="ghost" disabled={!enabled} onClick={() => setEditStudy(true)}>Study details</Button></div>{facts.map(f => <article key={f.id} className="rounded-xl border bg-white p-6"><div className="flex flex-wrap items-center gap-2"><Status value={f.payload.status}/><span className="text-sm text-muted-foreground">{f.payload.product}</span><span className="ml-auto text-xs text-muted-foreground">Checked {f.payload.checkedAt}</span><Button size="sm" variant="ghost" disabled={!enabled} onClick={() => setRecordForm({ kind: "fact", record: f })}>Edit</Button></div><h2 className="mt-4 text-base font-semibold">{f.payload.claim}</h2><blockquote className="my-4 border-l-2 border-blue-200 pl-4 text-sm leading-7 text-slate-600">{f.payload.excerpt}</blockquote><SourceLink url={f.payload.source}/>{f.payload.notes && <p className="mt-3 text-sm text-muted-foreground">{f.payload.notes}</p>}</article>)}{!facts.length && <Empty title="Add the facts a customer should be able to verify" description="Include a product version, exact source excerpt, and date. These references support your reviews; they are not injected into collection questions."/>}<Note>Preferred positioning is not automatically a verified fact. Earlier claim reviews retain the reference version used when they were saved.</Note></div>}
      {study && section === "questions" && <div className="space-y-5"><QuestionTools study={study} records={records} enabled={enabled} onRefresh={refresh}/>{questions.length ? <div className="overflow-hidden rounded-xl border bg-white"><Table><TableHeader><TableRow><TableHead className="pl-5">Question</TableHead><TableHead>Intent / origin</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{questions.map(q => <TableRow key={q.id}><TableCell className="max-w-xl whitespace-normal py-5 pl-5"><p className="text-sm font-medium leading-6">{q.payload.prompt}</p>{q.payload.notes && <p className="mt-2 text-xs leading-5 text-muted-foreground">{q.payload.notes}</p>}</TableCell><TableCell className="text-sm capitalize">{q.payload.intent}<span className="mt-1 block text-xs text-muted-foreground">{(q.payload.origin || "researcher").replaceAll("_", " ")}</span></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" disabled={!enabled} onClick={() => setRecordForm({ kind: "question", record: q })}>Edit</Button><Button size="sm" variant="outline" disabled={!enabled} onClick={() => setCollect({ prompt: q.payload.prompt })}>Use<ArrowRight size={14}/></Button></TableCell></TableRow>)}</TableBody></Table></div> : <Empty title="Save the questions that matter" description="Bring questions from sales conversations, customer support, and actual research. Starter questions can help define an initial study."/>}<Button variant="outline" onClick={() => navigate("collect")}>Build a collection plan<ArrowRight size={15}/></Button></div>}
      {study && section === "compare" && <Suspense fallback={<p role="status">Opening comparison…</p>}><ComparePage runs={visibleRuns}/></Suspense>}{section === "connections" && <ConnectionsPage value={connections} onChange={setConnections} enabled={enabled}/>}{section === "method" && <MethodPage/>}
    </div><footer className="mt-auto flex flex-wrap justify-between gap-2 px-8 py-6 text-xs text-muted-foreground"><span>Brand Research / Evidence workspace</span><span>Original records. Visible uncertainty.</span></footer>
  </SidebarInset><Toaster position="bottom-right"/>
    {onboarding && <Onboarding study={onboarding === "edit" ? study : undefined} onClose={() => setOnboarding(null)} onSaved={async id => { await refresh(id); navigate("overview"); toast.success("Brand workspace saved."); }}/>} {editStudy && <StudyForm study={study} onClose={() => setEditStudy(false)} onSaved={async id => { await refresh(id); }}/>}
    {recordForm && study && <RecordForm {...recordForm} studyId={study.id} runId={recordForm.record?.payload.runId || selectedId} facts={facts} onClose={() => setRecordForm(null)} onSaved={async () => { await refresh(); toast.success("Research record saved."); }}/>}
    {collect && study && <CollectForm studyId={study.id} initialPrompt={collect.prompt} initialMode={collect.mode} connections={connections} onClose={() => setCollect(null)} onConnect={() => { setCollect(null); navigate("connections"); }} onSaved={async id => { navigate("observations"); await refresh(study.id, id); toast.success("Observation saved."); }}/>}
  </SidebarProvider>;
}
function Empty({ title, description }: { title: string; description: string }) { return <div className="rounded-xl border bg-white px-6 py-16 text-center"><MessageSquareText size={30} className="mx-auto mb-5 text-slate-300"/><h2 className="font-semibold">{title}</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-muted-foreground">{description}</p></div>; }
