export type Capability={id:string;surface:string;method:string;capture:string[];limits:string[];status:string;documentation?:string};
const apiLimits=["Not a reproduction of the signed-in consumer application","Private reasoning, full candidate-source sets, and rejection explanations are unavailable","Live model/tool support requires validation with the connected account"];
export const capabilities:Capability[]=[
 {id:"openai",surface:"OpenAI Responses",method:"Provider API or original JSON import",capture:["Original request and response","Disclosed web-search tool events","Native citation fields and eligible exact offsets","Usage and completion status"],limits:apiLimits,status:"Implemented · fixture tested",documentation:"https://developers.openai.com/api/docs/guides/tools-web-search"},
 {id:"anthropic",surface:"Anthropic Messages",method:"Provider API or original JSON import",capture:["Original request and response","Disclosed search results and tool-use blocks","Native citations and provider excerpts","Usage and completion status"],limits:[...apiLimits,"Text-block citations are not automatically exact sentence attribution"],status:"Implemented · fixture tested",documentation:"https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool"},
 {id:"gemini",surface:"Gemini Interactions",method:"Provider API or original JSON import",capture:["Original request and response","Returned text and disclosed search content","Native grounding fields where returned","Usage and completion status"],limits:[...apiLimits,"Grounding metadata varies by model and response format"],status:"Implemented · fixture tested",documentation:"https://ai.google.dev/gemini-api/docs/interactions-overview"},
 {id:"perplexity_api",surface:"Perplexity Sonar",method:"Provider API or original JSON import",capture:["Original request and response","Citations distinguished from returned search results","Completion and usage fields"],limits:apiLimits,status:"Implemented · fixture tested",documentation:"https://docs.perplexity.ai/api-reference/sonar-post"},
 {id:"xai",surface:"xAI Responses",method:"Provider API or original JSON import",capture:["Original request and response","Disclosed web-search events and sources","Native citation fields and usage"],limits:apiLimits,status:"Implemented · fixture tested",documentation:"https://docs.x.ai/developers/tools/web-search"},
 ...["ChatGPT","Claude","Gemini app","Google AI Mode","Google AI Overviews","Perplexity app","Microsoft Copilot","Grok","Other consumer app"].map(surface=>({id:`consumer-${surface}`,surface,method:"Human-observed capture or manual recording",capture:["The answer a person actually observed","Visible links selected by the recorder","Recorded date, mode, locale and conversation conditions","Screenshots attached to the observation"],limits:["No autonomous signed-in collector is implemented","A recorded link is not automatically a provider-attributed citation","Capture completeness and context depend on the person recording it","Personalization and hidden retrieval remain unobservable"],status:"Capture workflow implemented · real-app validation pending"})),
];
