import type { Normalized, ResearchRecord, Run, Study } from "./research";
export const exampleStudy: Study = { id: "example-study", name: "Aster · product understanding", brand: "Aster (fictional)", website: "https://example.com", objective: "A synthetic example: inspect how a fictional coffee maker is described and trace a product claim to its cited source.", created_at: "2026-09-17T10:00:00Z" };
const normalized: Normalized = { parser_version: "example-1.0", provider: "openai", completion: "complete", native_status: "completed", model_reported: "Synthetic example", provider_response_id: null, usage: null,
  segments: [{ text: "The Aster One is a compact coffee maker designed for travel. Its removable filter basket can be rinsed after use.\n\nFor cleaning, follow the product care guide: hand-wash the filter basket and wipe the base with a damp cloth. Do not immerse the base in water.", raw_path: "$.output[1].content[0]" }],
  tool_events: [{ raw_path: "$.output[0]", native: { type: "web_search_call", status: "completed", action: { type: "search", queries: ["Aster One coffee maker cleaning care guide"], sources: [{ url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)" }, { url: "https://example.com/travel-coffee-comparison", title: "Travel coffee comparison (fictional)" }] } } }],
  sources: [{ url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)", role: "cited", raw_path: "$.output[1].content[0].annotations[0]" }, { url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)", role: "provider_disclosed_consulted", raw_path: "$.output[0].action.sources[0]" }, { url: "https://example.com/travel-coffee-comparison", title: "Travel coffee comparison (fictional)", role: "provider_disclosed_consulted", raw_path: "$.output[0].action.sources[1]" }],
  citations: [{ segment_index: 0, raw_path: "$.output[1].content[0].annotations[0]", native: { type: "url_citation", url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)" } }], warnings: ["Synthetic training example. No provider was queried and these are not real products or findings."], unparsed_top_level_events: [], search_observation: "tool_activity_disclosed", rejected_sources: null, private_ranking_reasons: null };
export const exampleRuns: Run[] = [{ id: "example-run", study_id: "example-study", provider: "openai", environment: "api", model: "Synthetic example", prompt: "How do I clean the Aster One coffee maker?", status: "complete", search: "auto", settings: { synthetic: true, notes: "Example only. No real API request." }, normalized, error: null, created_at: "2026-09-17T10:04:00Z", finished_at: "2026-09-17T10:04:01Z", evidence_hash: null, attachments: [] }];
export const exampleRecords: ResearchRecord[] = [{ id: "example-fact", study_id: "example-study", kind: "fact", payload: { claim: "The Aster One filter basket should be hand-washed.", product: "Aster One (fictional)", source: "https://example.com/aster-one/care", excerpt: "Hand-wash the filter basket. Wipe the base; do not immerse it.", checkedAt: "2026-09-17", status: "verified", notes: "Synthetic source and fact for learning the interface." }, created_at: "2026-09-17T10:00:00Z", updated_at: "2026-09-17T10:00:00Z" }, { id: "example-review", study_id: "example-study", kind: "review", payload: { runId: "example-run", claim: "Hand-wash the filter basket.", verdict: "supported", evidenceLevel: "observed", materiality: "medium", factIds: ["example-fact"], explanation: "In this synthetic example, the answer agrees with the supplied care-guide excerpt. The citation points to the same page.", hypothesis: "The care guide may have supplied the cleaning instruction. The citation alone does not prove how the model selected it.", nextTest: "Repeat the same question and compare the cited pages and wording." }, created_at: "2026-09-17T10:05:00Z", updated_at: "2026-09-17T10:05:00Z" }, { id: "example-question", study_id: "example-study", kind: "question", payload: { prompt: "How do I clean the Aster One coffee maker?", intent: "support", notes: "Synthetic customer question." }, created_at: "2026-09-17T10:00:00Z", updated_at: "2026-09-17T10:00:00Z" }];

// The example uses the same exact-passage workflow as saved client records.
const exampleStart = normalized.segments[0].text.indexOf("For cleaning");
const exampleEnd = normalized.segments[0].text.indexOf("Do not immerse");
normalized.citations[0].native.start_index = exampleStart;
normalized.citations[0].native.end_index = exampleEnd;
exampleRecords[1].payload.claim = normalized.segments[0].text.slice(exampleStart, exampleEnd);
exampleRecords[1].payload.anchor = { segmentIndex: 0, start: exampleStart, end: exampleEnd };
exampleRecords[1].payload.impact = "Customers receive the intended care instructions for this fictional product. This reviewed claim does not establish how other questions or platforms perform.";
exampleRecords[1].payload.recommendation = "Keep the care guide accessible and repeat the cleaning question after product instructions change. No correction is indicated by this one example.";
