import type { Normalized, ResearchRecord, Run, Study } from "./research";
export const exampleStudy: Study = { id: "example-study", name: "Aster · product understanding", brand: "Aster (fictional)", website: "https://example.com", objective: "A synthetic example: inspect how a fictional coffee maker is described and trace a product claim to its cited source.", created_at: "2026-09-17T10:00:00Z" };
const normalized: Normalized = { parser_version: "example-1.0", provider: "openai", completion: "complete", native_status: "completed", model_reported: "Synthetic example", provider_response_id: null, usage: null,
  segments: [{ text: "The Aster One is a compact coffee maker designed for travel. Its removable filter basket can be rinsed after use.\n\nFor cleaning, follow the product care guide: hand-wash the filter basket and wipe the base with a damp cloth. Do not immerse the base in water.", raw_path: "$.output[1].content[0]" }],
  tool_events: [{ raw_path: "$.output[0]", native: { type: "web_search_call", status: "completed", action: { type: "search", queries: ["Aster One coffee maker cleaning care guide"], sources: [{ url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)" }, { url: "https://example.com/travel-coffee-comparison", title: "Travel coffee comparison (fictional)" }] } } }],
  sources: [{ url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)", role: "cited", raw_path: "$.output[1].content[0].annotations[0]" }, { url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)", role: "provider_disclosed_consulted", raw_path: "$.output[0].action.sources[0]" }, { url: "https://example.com/travel-coffee-comparison", title: "Travel coffee comparison (fictional)", role: "provider_disclosed_consulted", raw_path: "$.output[0].action.sources[1]" }],
  citations: [{ segment_index: 0, raw_path: "$.output[1].content[0].annotations[0]", native: { type: "url_citation", url: "https://example.com/aster-one/care", title: "Aster One care guide (fictional)" } }], warnings: ["Synthetic training example. No provider was queried and these are not real products or findings."], unparsed_top_level_events: [], search_observation: "tool_activity_disclosed", rejected_sources: null, private_ranking_reasons: null };
export const exampleRuns: Run[] = [{ id: "example-run", study_id: "example-study", provider: "openai", environment: "api", model: "Synthetic example", prompt: "How do I clean the Aster One coffee maker?", status: "complete", search: "auto", settings: { synthetic: true, notes: "Example only. No real API request." }, normalized, error: null, created_at: "2026-09-17T10:04:00Z", finished_at: "2026-09-17T10:04:01Z", evidence_hash: null, attachments: [] }];
export const exampleRecords: ResearchRecord[] = [{ id: "example-fact", study_id: "example-study", kind: "fact", payload: { claim: "The Aster One filter basket should be hand-washed.", product: "Aster One (fictional)", source: "https://example.com/aster-one/care", excerpt: "Hand-wash the filter basket. Wipe the base; do not immerse it.", checkedAt: "2026-09-17", status: "verified", notes: "Synthetic source and fact for learning the interface." }, created_at: "2026-09-17T10:00:00Z", updated_at: "2026-09-17T10:00:00Z" }, { id: "example-review", study_id: "example-study", kind: "review", payload: { runId: "example-run", claim: "Hand-wash the filter basket.", verdict: "supported", evidenceLevel: "observed", materiality: "medium", factIds: ["example-fact"], explanation: "In this synthetic example, the answer agrees with the supplied care-guide excerpt. The citation points to the same page.", hypothesis: "The care guide may have supplied the cleaning instruction. The citation alone does not prove how the model selected it.", nextTest: "Repeat the same question and compare the cited pages and wording." }, created_at: "2026-09-17T10:05:00Z", updated_at: "2026-09-17T10:05:00Z" }, { id: "example-question", study_id: "example-study", kind: "question", payload: { prompt: "How do I clean the Aster One coffee maker?", intent: "support", notes: "Synthetic customer question." }, created_at: "2026-09-17T10:00:00Z", updated_at: "2026-09-17T10:00:00Z" }];

// The example uses the same exact-passage workflow as saved client records.
const exampleStart = normalized.segments[0].text.indexOf("For cleaning");
const exampleEnd = normalized.segments[0].text.indexOf("Do not immerse");
normalized.citations[0].native.start_index = exampleStart;
normalized.citations[0].native.end_index = exampleEnd;
exampleRecords[1].payload.claim = normalized.segments[0].text.slice(exampleStart, exampleEnd);
exampleRecords[1].payload.anchor = { segmentIndex: 0, start: exampleStart, end: exampleEnd };
exampleRecords[1].payload.impact = "Customers receive the intended care instructions for this fictional product. This reviewed claim does not establish how other questions or platforms perform.";
exampleRecords[1].payload.recommendation = "Keep the care guide accessible and repeat the cleaning question after product instructions change. No correction is indicated by this one example.";

exampleStudy.profile = {
  category: "compact coffee makers", audience: "people making coffee in small kitchens and while travelling",
  positioning: "Thoughtful coffee for small spaces: compact, repairable, and easy to care for. Travel is one use case, not the whole brand.",
  aliases: ["Aster", "Aster One"], competitors: [{ name: "Fern", aliases: ["Fern Mini"] }, { name: "Hearth", aliases: [] }], market: "United States", language: "English",
};
const syntheticAnswers = [
  { provider: "anthropic", date: "2026-09-18", prompt: "Which compact coffee makers work well in a small kitchen?", text: "For a small kitchen, Aster One and Fern Mini are worth comparing. Aster One has a compact footprint and a removable basket, while Fern Mini prioritizes a lower price. Check the current specifications and care instructions before buying.", intent: "discovery" },
  { provider: "openai", date: "2026-09-18", prompt: "What is Aster known for?", text: "Aster is best known for compact coffee makers for travel. The Aster One is easy to pack and has a removable filter basket. The care guide says to hand-wash the basket and keep the base out of water.", intent: "verification" },
  { provider: "anthropic", date: "2026-09-19", prompt: "Which compact coffee makers offer good value?", text: "Fern Mini is a useful starting point for buyers focused on price. Hearth offers a larger range of countertop machines. Compare total cost, repair support, and care requirements before choosing.", intent: "purchase" },
  { provider: "openai", date: "2026-09-19", prompt: "How does Aster compare with Fern for everyday use?", text: "Aster One emphasizes a compact design and a removable basket. Fern Mini emphasizes affordability. For everyday use, compare warranty coverage and whether replacement parts are available; these details are not established by this answer.", intent: "comparison" },
] as const;
syntheticAnswers.forEach((item, i) => {
  const n: Normalized = { ...structuredClone(normalized), provider: item.provider, segments: [{ text: item.text, raw_path: "$.synthetic.answer" }], citations: [], tool_events: [], sources: [{ url: "https://example.com/compact-coffee-comparison", title: "Compact coffee comparison (fictional)", role: "provider_disclosed_consulted", raw_path: "$.synthetic.sources[0]" }], search_observation: "tool_activity_disclosed" };
  exampleRuns.push({ ...exampleRuns[0], id: `example-run-${i + 2}`, provider: item.provider, prompt: item.prompt, normalized: n, settings: { synthetic: true, intent: item.intent, notes: "Entirely fictional illustration; no API was called." }, created_at: `${item.date}T10:00:00Z`, finished_at: `${item.date}T10:00:01Z` });
  exampleRecords.push({ id: `example-question-${i + 2}`, study_id: exampleStudy.id, kind: "question", payload: { prompt: item.prompt, intent: item.intent, origin: "researcher", notes: "Synthetic question for demonstrating the workspace." }, created_at: `${item.date}T09:00:00Z`, updated_at: `${item.date}T09:00:00Z` });
});
exampleRecords.push({ id: "example-analysis", study_id: exampleStudy.id, kind: "analysis", payload: { status: "needs_review", provider: "openai", model: "Synthetic illustration, not model output", inputRunIds: exampleRuns.map(r => r.id), inputFacts: [exampleRecords[0]], rejectedEvidence: 0, themes: [
  { title: "Recognized for portability. Less visible for everyday living.", description: "In this fictional set, compactness and travel recur. The intended themes of repairability and everyday use have less explicit support in the recorded language. Review the passages before deciding whether that gap matters.", tone: "mixed", evidence: [{ runId: "example-run-3", quote: "Aster is best known for compact coffee makers for travel." }, { runId: "example-run-5", quote: "For everyday use, compare warranty coverage and whether replacement parts are available; these details are not established by this answer." }] },
  { title: "Care instructions have a clearer evidence trail.", description: "The cleaning observation contains an attributed care instruction that a researcher has compared with a dated reference.", tone: "positive", evidence: [{ runId: "example-run", quote: "For cleaning, follow the product care guide: hand-wash the filter basket and wipe the base with a damp cloth." }] },
], findings: [{ title: "Test the everyday-use positioning", type: "positioning", explanation: "The fictional response foregrounds travel. That is a positioning observation, not a factual error or proof of how the provider selected its sources.", recommendation: "Collect repeated, unbranded small-kitchen questions across comparable conditions before proposing a content change.", factIds: [], status: "needs_review", evidence: [{ runId: "example-run-3", quote: "Aster is best known for compact coffee makers for travel." }] }] }, created_at: "2026-09-19T12:00:00Z", updated_at: "2026-09-19T12:00:00Z" });
exampleRecords.push({ id: "example-source", study_id: exampleStudy.id, kind: "source", payload: { url: "https://example.com/aster-one/care", title: "Fictional care-guide capture", excerpt: "Hand-wash the filter basket. Wipe the base; do not immerse it.", provenance: "researcher_supplied_capture", capturedAt: "2026-09-17T10:00:00Z", notes: "Synthetic excerpt. Not fetched from a real product page.", contentHash: "Synthetic example — no source fingerprint" }, created_at: "2026-09-17T10:00:00Z", updated_at: "2026-09-17T10:00:00Z" });
exampleRecords.push({ id: "example-action", study_id: exampleStudy.id, kind: "action", payload: { title: "Repeat the cleaning question after the next care-guide revision", description: "The reviewed instruction agrees with the reference. Monitor a comparable question set after a real product update; there is no demonstrated correction to make now.", status: "proposed", priority: "low", reviewIds: ["example-review"], verification: "Compare the exact care instructions and references in a new set of observations. Retain model and method labels.", verificationRunIds: [], dueDate: "", implementedAt: "" }, created_at: "2026-09-19T12:00:00Z", updated_at: "2026-09-19T12:00:00Z" });

// Seed the connected workflow without issuing any real provider or source requests.
exampleRuns[0].settings={...exampleRuns[0].settings,questionId:'example-question',questionVersion:'2026-09-17T10:00:00Z'};
const consumerAnswer='The Aster One filter basket is dishwasher safe. It is designed for compact kitchens.';
exampleRuns.push({...exampleRuns[0],id:'example-consumer',provider:'chatgpt',environment:'consumer',status:'manually_recorded',model:'Unknown · fictional consumer observation',prompt:exampleRuns[0].prompt,settings:{synthetic:true,location:'Miami · fictional',memory:'Unknown',conversation:'New conversation · fictional',mode:'Search visible · fictional'},normalized:{...structuredClone(normalized),provider:'chatgpt',completion:'manually_recorded',segments:[{text:consumerAnswer,raw_path:'$.observation.answer'}],citations:[],tool_events:[],sources:[{url:'https://example.com/aster-one/care',title:'Care guide (fictional)',role:'manually_recorded_link',raw_path:'$.observation.sources[0]'}]}});
exampleRuns.push({...exampleRuns[0],id:'example-failed',status:'failed',error:'Fictional interrupted request. No paid request occurred.',normalized:null});
for(const [i,surface] of ['api:openai','consumer:chatgpt','consumer:claude'].entries())exampleRecords.push({id:`example-coverage-${i}`,study_id:exampleStudy.id,kind:'coverage',payload:{questionId:'example-question',questionVersion:'2026-09-17T10:00:00Z',prompt:exampleRuns[0].prompt,context:{market:'United States',language:'English',purpose:'baseline'},surface,expected:2},created_at:'2026-09-17T10:00:00Z',updated_at:'2026-09-17T10:00:00Z'});
exampleRecords.push({id:'example-assignment',study_id:exampleStudy.id,kind:'assignment',payload:{runId:'example-consumer',targetId:'example-coverage-1'},created_at:'2026-09-17T10:00:00Z',updated_at:'2026-09-17T10:00:00Z'});
exampleRecords.push({id:'example-review-task',study_id:exampleStudy.id,kind:'review_task',payload:{runId:'example-consumer',claim:'The Aster One filter basket is dishwasher safe. ',anchor:{segmentIndex:0,start:0,end:47},provider:'chatgpt',environment:'consumer',priority:'high',productId:''},created_at:'2026-09-17T10:00:00Z',updated_at:'2026-09-17T10:00:00Z'});
exampleRecords.at(-1)!.payload.anchor.end=exampleRecords.at(-1)!.payload.claim.length;
exampleRecords.push({id:'example-unavailable-source',study_id:exampleStudy.id,kind:'source',payload:{url:'https://example.com/aster-one/care',runId:'example-consumer',provenance:'application_capture_attempt',status:'unavailable',capturedAt:'2026-09-19T10:00:00Z',error:'Fictional unavailable capture. No real website was requested.',excerpt:''},created_at:'2026-09-19T10:00:00Z',updated_at:'2026-09-19T10:00:00Z'});
