import { db, AppError, publicRecord, publicRun } from './server';
import type { ResearchRecord, Run } from './research';
import { coverageBoard, type ObservationSummary } from './investigation';
export async function studyRecords(uid:string,studyId:string):Promise<ResearchRecord[]>{return (await db().prepare('SELECT * FROM records WHERE owner_id=? AND study_id=? ORDER BY created_at DESC,id DESC').bind(uid,studyId).all()).results.map(publicRecord);}
export async function coverageData(uid:string,studyId:string,records?:ResearchRecord[]){
  const all=records||await studyRecords(uid,studyId);const runs:ObservationSummary[]=[];let cursor='';
  for(;;){const page=await db().prepare("SELECT id,provider,environment,status,model,prompt,created_at,settings,CASE WHEN EXISTS(SELECT 1 FROM json_each(COALESCE(normalized,'{}'),'$.segments') WHERE length(trim(json_extract(value,'$.text')))>0) THEN 1 ELSE 0 END AS hasAnswer FROM runs WHERE owner_id=? AND study_id=? AND id>? ORDER BY id LIMIT 200").bind(uid,studyId,cursor).all<Record<string,unknown>>();for(const r of page.results)runs.push({...r,settings:JSON.parse(String(r.settings)),hasAnswer:!!r.hasAnswer} as ObservationSummary);if(page.results.length<200)break;cursor=String(page.results.at(-1)!.id);}
  const jobs=(await db().prepare('SELECT question_id,provider,status,run_id,settings FROM collection_jobs WHERE owner_id=? AND study_id=?').bind(uid,studyId).all<{question_id:string|null;provider:string;status:string;run_id:string|null;settings:string}>()).results.map(j=>({...j,settings:JSON.parse(j.settings)}));return coverageBoard(all,runs,jobs);
}
export async function getStudyRun(uid:string,studyId:string,id:string):Promise<Run>{const row=await db().prepare('SELECT * FROM runs WHERE id=? AND owner_id=? AND study_id=?').bind(id,uid,studyId).first();if(!row)throw new AppError('Observation not found in this study.',404);return publicRun(row);}
export async function putRecord(uid:string,studyId:string,kind:string,payload:unknown,id?:string,version?:string){
  const now=new Date().toISOString();if(id){const old=await db().prepare('SELECT * FROM records WHERE id=? AND owner_id=? AND study_id=? AND kind=?').bind(id,uid,studyId,kind).first();if(!old)throw new AppError('Record not found.',404);if(version!==old.updated_at)throw new AppError('This record changed. Reload before saving.',409);const result=await db().batch([db().prepare('INSERT INTO record_history(id,record_id,owner_id,study_id,kind,payload,recorded_at) SELECT ?,id,owner_id,study_id,kind,payload,? FROM records WHERE id=? AND owner_id=? AND updated_at=?').bind(crypto.randomUUID(),now,id,uid,version),db().prepare('UPDATE records SET payload=?,updated_at=? WHERE id=? AND owner_id=? AND updated_at=?').bind(JSON.stringify(payload),now,id,uid,version)]);if(result[1].meta.changes!==1)throw new AppError('This record changed. Reload before saving.',409);return id;}
  id=crypto.randomUUID();try{await db().prepare('INSERT INTO records(id,owner_id,study_id,kind,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,uid,studyId,kind,JSON.stringify(payload),now,now).run();}catch(e){if(String(e).includes("UNIQUE")||String((e as {cause?:unknown}).cause).includes("UNIQUE"))throw new AppError("This item was saved in another session. Reload before editing.",409);throw e;}return id;
}
